import {notFound} from "next/navigation";
import {PortalShell,PortalTopbar} from "../../../../../components/portal/PortalShell";
import {BackLink} from "../../../../../components/portal/BackLink";
import {DailyReportForm} from "../../../../../components/portal/DailyReportForm";
import {saveDailyReportAction} from "../../new/actions";
import {getProject,getReport,listAttendanceForReport,listProjectElements,listProjectWorkforce,listReportElements,listReportWeather} from "../../../../../lib/repositories";
import {requireUser} from "../../../../../lib/auth";
import {canAccessProject,canReviewDailyReports} from "../../../../../lib/permissions";
import {getPortalLanguage} from "../../../../../lib/portal-locale";
import {portalText} from "../../../../../data/portal-i18n";
export default async function EditReportPage({params}:{params:Promise<{id:string}>}){const{id}=await params,report=getReport(Number(id));if(!report)notFound();const user=await requireUser();if(!canAccessProject(user,report.projectId)||report.status==="Approved"||(!canReviewDailyReports(user)&&(report.reporterUserId!==user.id||report.status!=="Draft")))notFound();const project=getProject(report.projectId);if(!project)notFound();const language=await getPortalLanguage(),t=(v:string)=>portalText(language,v),selected=listReportElements(report.id),available=listProjectElements(project.id,{available:true}),elementMap=new Map([...available,...selected].map((element)=>[element.id,element])),crew={project:{...project},employees:listProjectWorkforce(project.id).map((employee)=>({...employee,certificates:[...employee.certificates]})),elements:[...elementMap.values()].map((element)=>({...element}))};return <PortalShell active="/portal/reports"><BackLink href={`/portal/reports/${report.id}`} label={t("Back to report")}/><PortalTopbar eyebrow={project.name} title={t("Edit daily report")}/><DailyReportForm action={saveDailyReportAction} crews={[crew]} report={{...report}} entries={listAttendanceForReport(report.id).map((entry)=>({...entry}))} selectedElements={selected.map((element)=>({...element}))} weatherRows={listReportWeather(report.id).map((row)=>({...row}))} language={language} today={report.date}/></PortalShell>}
