import test from "node:test";
import assert from "node:assert/strict";
import {generateDailyReportArchivePdf,generateDailyReportPdf,dailyReportArchiveFilename,dailyReportPdfFilename,dailyReportPdfWeatherModel,dailyReportRevision} from "../lib/daily-report-pdf.ts";
import type {AttendanceEntry,DailyReport,ProjectPhoto,ReportWeather} from "../lib/repositories.ts";

const report:DailyReport={id:42,projectId:"p1",project:"Rīga монтаж",date:"2026-08-09",people:2,work:"Uzstādīti paneļi",deliveries:0,issues:0,weather:"Dry",notes:"",author:"Jānis Bērziņš",reporterUserId:1,reporterEmployeeId:null,status:"Submitted",materials:"Панели доставлены",equipment:"Crane",problems:"",safety:"No incidents",additionalNotes:"",createdAt:"2026-08-09 12:00:00",updatedAt:"2026-08-09 12:00:00",submittedAt:"2026-08-09 12:00:00",approvedById:null,approvedAt:""};
const attendance:AttendanceEntry[]=[{id:1,reportId:42,employeeId:"e1",employeeName:"Jānis Bērziņš",position:"Welder",projectId:"p1",projectName:report.project,date:report.date,status:"Worked",regularHours:8,overtimeHours:2,comment:"Монтаж"},{id:2,reportId:42,employeeId:"e2",employeeName:"Andris Krūmiņš",position:"Rigger",projectId:"p1",projectName:report.project,date:report.date,status:"Sick leave",regularHours:0,overtimeHours:0,comment:""}];
const weather:ReportWeather[]=["07:00","10:00","14:00","17:00"].map((timepoint,index)=>({id:index+1,reportId:42,timepoint,temperature:12+index,conditionCode:index?3:0,condition:index?"Cloudy":"Clear",precipitation:0,windSpeed:3+index,windGust:5+index,provider:"Open-Meteo",retrievedAt:"2026-08-09T05:00:00Z"}));

test("Daily Report renderer creates a genuine paginated PDF with LV/RU data and weather",async()=>{const pdf=await generateDailyReportPdf({report,attendance,photos:[],weather,language:"ru"});assert.equal(pdf.subarray(0,5).toString(),"%PDF-");assert.ok(pdf.length>5000);assert.match(pdf.toString("latin1"),/\/Type \/Page/);assert.match(pdf.toString("latin1"),/\/Title/);});
test("persisted weather model includes full and partial snapshots without losing a manual note",()=>{const full=dailyReportPdfWeatherModel(report,weather,"en");assert.equal(full.summary,"07:00 · 10:00 · 14:00 · 17:00");assert.equal(full.lines.length,4);assert.match(full.lines[0],/Precipitation 0 mm/);assert.match(full.lines[0],/Wind 3 m\/s/);assert.match(full.lines[0],/Gust 5 m\/s/);assert.equal(full.manualNote,"Dry");const partial=dailyReportPdfWeatherModel(report,[weather[0],weather[2]],"lv");assert.equal(partial.lines.length,2);assert.match(partial.lines[0],/Nokrišņi/);});
test("manual-note and zero-weather fallbacks remain deterministic",()=>{const manual=dailyReportPdfWeatherModel(report,[],"en"),empty=dailyReportPdfWeatherModel({...report,weather:""},[],"en"),approved:DailyReport={...report,status:"Approved"};assert.equal(manual.summary,"Dry");assert.equal(manual.lines.length,0);assert.equal(empty.summary,"—");assert.equal(empty.manualNote,"");assert.deepEqual(dailyReportPdfWeatherModel(approved,weather,"en"),dailyReportPdfWeatherModel(approved,weather,"en"));});
test("Daily Report PDF filenames are safe and descriptive",()=>{const filename=dailyReportPdfFilename(report);assert.ok(filename.endsWith(".pdf"));assert.doesNotMatch(filename,/[\\/]/);assert.match(filename,/42-2026-08-09/);});
test("Daily Report revisions are stable and change when the report changes",()=>{assert.equal(dailyReportRevision(report),"R-20260809120000Z");assert.notEqual(dailyReportRevision({...report,updatedAt:"2026-08-10 07:30:15"}),dailyReportRevision(report));});
test("Monthly archive is a real PDF with weather and chronologically ordered reports",async()=>{const earlier={...report,id:41,date:"2026-08-01",updatedAt:"2026-08-01 08:00:00"};const pdf=await generateDailyReportArchivePdf({project:report.project,period:"2026-08",records:[{report:earlier,attendance:[],photos:[],weather:[],approvedBy:""},{report,attendance,photos:[],weather,approvedBy:""}],language:"lv"});assert.equal(pdf.subarray(0,5).toString(),"%PDF-");assert.ok((pdf.toString("latin1").match(/\/Type \/Page\b/g)??[]).length>=3);assert.ok(dailyReportArchiveFilename(report.project,"2026-08").endsWith(".pdf"));});
test("a normal three-worker report with weather and two photos stays on one A4 page",async()=>{const third={...attendance[0],id:3,employeeId:"e3",employeeName:"Test Montētājs",regularHours:6,overtimeHours:2};const photos:ProjectPhoto[]=[1,2].map((id)=>({id,projectId:report.projectId,reportId:report.id,photoDate:report.date,area:"Zone A",caption:`Site photo ${id}`,fileRef:"",author:report.author,notes:"",originalFilename:`photo-${id}.jpg`,storedPath:`photos/missing-${id}.jpg`,fileSize:100,mimeType:"image/jpeg",uploadedById:1,uploadedAt:report.updatedAt}));const pdf=await generateDailyReportPdf({report,attendance:[...attendance,third],photos,weather,language:"en"});assert.equal((pdf.toString("latin1").match(/\/Type \/Page\b/g)??[]).length,1);});
