import test from "node:test";import assert from "node:assert/strict";import {elementProgress,elementRoleCapabilities,filterElements,importHeaders,isInstallableStatus,parseElementCsv,validateInstallationSelection} from "../lib/elements.ts";import {portalText} from "../data/portal-i18n.ts";
const rows=[{id:1,code:"VS-100",elementType:"Wall panel",floor:"1",zone:"A",status:"Installed"},{id:2,code:"VS-101",elementType:"Wall panel",floor:"1",zone:"A",status:"On site"},{id:3,code:"HC-201",elementType:"Hollow core slab",floor:"1",zone:"B",status:"Issue"},{id:4,code:"ST-01",elementType:"Stair",floor:"1",zone:"B",status:"Planned"}];
test("project element identity import rejects existing and in-file duplicate marks",()=>{const csv=importHeaders.join(",")+"\nVS-100,Wall panel,1,A,,,,,,,,\nVS-101,Wall panel,1,A,,,,,,,,\nvs-101,Wall panel,1,A,,,,,,,,";const result=parseElementCsv(csv,["VS-100"]);assert.equal(result.candidates.length,1);assert.equal(result.errors.length,2);assert.match(result.errors.join(" "),/Duplicate element code/);});
test("element filtering is project-register filter compatible",()=>{assert.deepEqual(filterElements(rows,{floor:"1",zone:"A",type:"Wall panel"}).map((row)=>row.code),["VS-100","VS-101"]);assert.deepEqual(filterElements(rows,{q:"HC-201"}).map((row)=>row.id),[3]);});
test("progress uses official installed status only",()=>{const progress=elementProgress(rows);assert.deepEqual({total:progress.total,installed:progress.installed,remaining:progress.remaining,percentage:progress.percentage},{total:4,installed:1,remaining:3,percentage:25});assert.equal(progress.byType.find((row)=>row.value==="Wall panel")?.installed,1);});
test("installed and blocked elements are excluded from normal installation",()=>{assert.equal(isInstallableStatus("Installed"),false);assert.equal(isInstallableStatus("Issue"),false);assert.equal(isInstallableStatus("Rejected / Hold"),false);assert.equal(isInstallableStatus("On site"),true);assert.equal(validateInstallationSelection(rows,[2,4]).valid,true);assert.equal(validateInstallationSelection(rows,[1]).valid,false);assert.equal(validateInstallationSelection(rows,[2,2]).valid,false);});
test("role foundation retains manager and foreman element responsibilities",()=>{assert.deepEqual(elementRoleCapabilities("Project Manager"),{view:true,operate:true,manage:true,correct:true});assert.deepEqual(elementRoleCapabilities("Foreman"),{view:true,operate:true,manage:false,correct:false});assert.equal(elementRoleCapabilities("Employee").view,false);});
test("Sprint 11 element labels are localized",()=>{assert.equal(portalText("lv","Element register"),"Elementu reģistrs");assert.equal(portalText("ru","Wall panel"),"Стеновая панель");assert.equal(portalText("lv","Installed"),"Uzmontēts");assert.equal(portalText("ru","Rejected / Hold"),"Отклонён / задержан");});
test("element detail metadata is localized without translating user data",()=>{assert.equal(portalText("lv","Weight"),"Svars");assert.equal(portalText("lv","Description"),"Apraksts");assert.equal(portalText("ru","Notes"),"Примечания");assert.equal(portalText("ru","Supplier"),"Поставщик");assert.equal(portalText("en","Installation date"),"Installation date");});
