"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "../../../lib/auth";
import { canAccessProject,canManageProjectOperations, canManageProjects } from "../../../lib/permissions";
import { createProjectDocument,createProjectPhoto,deleteProjectDocument,deleteProjectPhoto,getProject,getProjectDocument,getProjectPhoto,listProjectDocuments,logActivity,runTransaction,updateProjectDocumentMetadata,updateProjectPhotoMetadata } from "../../../lib/repositories";
import { removeStoredFile,storeUpload } from "../../../lib/storage";

const DOCUMENT_CATEGORIES=["Drawings","Method statements","DVP / DOP","HSE / Risk assessments","Quality","Delivery documents","Certificates","Contracts / Commercial","Other"] as const;
const OPERATIONAL_CATEGORIES=new Set(["Drawings","Method statements","DVP / DOP","HSE / Risk assessments","Quality","Delivery documents","Certificates","Other"]);
const DOCUMENT_STATUSES=["Current","Review","Archived"];
const text=(data:FormData,key:string,max:number)=>{const value=String(data.get(key)??"").trim();if(value.length>max)throw new Error(`${key} is too long.`);return value;};
const idValue=(data:FormData,key:string)=>{const value=Number(data.get(key));if(!Number.isInteger(value)||value<=0)throw new Error("Invalid record.");return value;};

export async function uploadDocumentAction(data:FormData){const user=await requireUser();if(!canManageProjectOperations(user))throw new Error("Document upload is not permitted.");const projectId=text(data,"projectId",80);const project=getProject(projectId);const category=text(data,"category",80);if(!project||!DOCUMENT_CATEGORIES.includes(category as typeof DOCUMENT_CATEGORIES[number]))throw new Error("Invalid project document.");if(!canManageProjects(user)&&!OPERATIONAL_CATEGORIES.has(category))throw new Error("This document category requires project-management permission.");const file=data.get("file");if(!(file instanceof File))throw new Error("Document file is required.");const title=text(data,"title",200);const revision=text(data,"revision",40);const documentDate=text(data,"documentDate",10);const status=text(data,"status",30);const description=text(data,"description",2000);if(!title||!revision||!documentDate||!DOCUMENT_STATUSES.includes(status))throw new Error("Document metadata is incomplete.");const stored=await storeUpload(file,"documents");try{const revisionExists=listProjectDocuments(projectId).some((document)=>document.title.toLowerCase()===title.toLowerCase());runTransaction(()=>{createProjectDocument({projectId,title,category,revision,documentDate,status,description,originalFilename:file.name,storedPath:stored.storedPath,fileSize:file.size,mimeType:file.type,uploadedById:user.id,uploadedBy:user.name});logActivity({userId:user.id,actor:user.name,action:revisionExists?"Document revision added":"Document uploaded",entityType:"project",entityId:projectId,details:`${title} · ${revision}`});});}catch(error){await removeStoredFile(stored.storedPath);throw error;}revalidatePath(`/portal/projects/${projectId}`);revalidatePath("/portal/documents");}
export async function uploadDocumentFormAction(_state:{error:string;success:string},data:FormData){try{await uploadDocumentAction(data);return {error:"",success:"Document uploaded."};}catch(error){return {error:error instanceof Error?error.message:"Document upload failed.",success:""};}}

export async function deleteDocumentAction(data:FormData){const user=await requireUser();if(!canManageProjects(user))throw new Error("Document deletion is not permitted.");const id=idValue(data,"id");const document=getProjectDocument(id);if(!document)throw new Error("Document not found.");runTransaction(()=>{deleteProjectDocument(id);logActivity({userId:user.id,actor:user.name,action:"Document deleted",entityType:"project",entityId:document.projectId,details:`${document.title} · ${document.revision}`});});await removeStoredFile(document.storedPath);revalidatePath(`/portal/projects/${document.projectId}`);revalidatePath("/portal/documents");}

export async function updateDocumentMetadataAction(data:FormData){const user=await requireUser();if(!canManageProjects(user))throw new Error("Document management is not permitted.");const id=idValue(data,"id");const document=getProjectDocument(id);const category=text(data,"category",80);const status=text(data,"status",30);const input={title:text(data,"title",200),category,revision:text(data,"revision",40),documentDate:text(data,"documentDate",10),status,description:text(data,"description",2000)};if(!document||!input.title||!input.revision||!input.documentDate||!DOCUMENT_CATEGORIES.includes(category as typeof DOCUMENT_CATEGORIES[number])||!DOCUMENT_STATUSES.includes(status))throw new Error("Invalid document metadata.");runTransaction(()=>{updateProjectDocumentMetadata(id,input);logActivity({userId:user.id,actor:user.name,action:"Document metadata updated",entityType:"project",entityId:document.projectId,details:`${input.title} · ${input.revision}`});});revalidatePath(`/portal/projects/${document.projectId}`);revalidatePath("/portal/documents");}

export async function uploadPhotoAction(data:FormData){const user=await requireUser();if(!canManageProjectOperations(user))throw new Error("Photo upload is not permitted.");const projectId=text(data,"projectId",80);if(!getProject(projectId)||!canAccessProject(user,projectId))throw new Error("Project not found.");const file=data.get("file");if(!(file instanceof File))throw new Error("Photo file is required.");const caption=text(data,"caption",240);const area=text(data,"area",160);const photoDate=text(data,"photoDate",10);const notes=text(data,"notes",2000);if(!caption||!photoDate)throw new Error("Photo caption and date are required.");const stored=await storeUpload(file,"photos");try{runTransaction(()=>{createProjectPhoto({projectId,photoDate,area,caption,author:user.name,notes,originalFilename:file.name,storedPath:stored.storedPath,fileSize:file.size,mimeType:file.type,uploadedById:user.id});logActivity({userId:user.id,actor:user.name,action:"Photo uploaded",entityType:"project",entityId:projectId,details:caption});});}catch(error){await removeStoredFile(stored.storedPath);throw error;}revalidatePath(`/portal/projects/${projectId}`);}
export async function uploadPhotoFormAction(_state:{error:string;success:string},data:FormData){try{await uploadPhotoAction(data);return {error:"",success:"Photo uploaded."};}catch(error){return {error:error instanceof Error?error.message:"Photo upload failed.",success:""};}}

export async function deletePhotoAction(data:FormData){const user=await requireUser();if(!canManageProjects(user))throw new Error("Photo deletion is not permitted.");const id=idValue(data,"id");const photo=getProjectPhoto(id);if(!photo||!canAccessProject(user,photo.projectId))throw new Error("Photo not found.");runTransaction(()=>{deleteProjectPhoto(id);logActivity({userId:user.id,actor:user.name,action:"Photo deleted",entityType:"project",entityId:photo.projectId,details:photo.caption});});await removeStoredFile(photo.storedPath);revalidatePath(`/portal/projects/${photo.projectId}`);}

export async function updatePhotoMetadataAction(data:FormData){const user=await requireUser();if(!canManageProjects(user))throw new Error("Photo management is not permitted.");const id=idValue(data,"id");const photo=getProjectPhoto(id);const input={photoDate:text(data,"photoDate",10),caption:text(data,"caption",240),area:text(data,"area",160),notes:text(data,"notes",2000)};if(!photo||!canAccessProject(user,photo.projectId)||!input.photoDate||!input.caption)throw new Error("Invalid photo metadata.");runTransaction(()=>{updateProjectPhotoMetadata(id,input);logActivity({userId:user.id,actor:user.name,action:"Photo metadata updated",entityType:"project",entityId:photo.projectId,details:input.caption});});revalidatePath(`/portal/projects/${photo.projectId}`);}
