import Link from "next/link";
import { notFound } from "next/navigation";
import { MetricCard } from "../../../../components/portal/MetricCard";
import { PortalShell, PortalTopbar, StatusBadge } from "../../../../components/portal/PortalShell";
import { ProjectDocumentsSection,ProjectPhotosSection } from "../../../../components/portal/ProjectMediaSections";
import { requireUser } from "../../../../lib/auth";
import { canManageProjectOperations, canManageProjects } from "../../../../lib/permissions";
import { appToday,formatAppDate,formatAppTime } from "../../../../lib/datetime";
import { getProject, listDeliveries, listDocuments, listEmployees, listProjectActivity, listProjectDocuments, listProjectIssues, listProjectMembers, listProjectPhotos, listReports } from "../../../../lib/repositories";
import { assignMemberAction, deleteDeliveryAction, deleteIssueAction, removeMemberAction, saveDeliveryAction, saveIssueAction, updateMemberRoleAction } from "../actions";
import { getPortalLanguage } from "../../../../lib/portal-locale";
import { portalText } from "../../../../data/portal-i18n";

const deliveryStatuses=["Planned","Confirmed","Received","Cancelled"];
const issueStatuses=["Open","In progress","Resolved","Closed"];
const priorities=["Low","Normal","High","Critical"];

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const project=getProject(id); if(!project)notFound();
  const language=await getPortalLanguage(); const t=(value:string)=>portalText(language,value);
  const user=await requireUser(); const canEdit=canManageProjects(user); const canOperate=canManageProjectOperations(user);
  const allEmployees=listEmployees(); const members=listProjectMembers(id); const memberIds=new Set(members.map((member)=>member.id)); const available=allEmployees.filter((employee)=>!memberIds.has(employee.id));
  const legacyDocuments=listDocuments().filter((document)=>document.project===project.name||document.project==="All projects"); const projectDocuments=listProjectDocuments(id); const reports=listReports().filter((report)=>report.projectId===id); const activity=listProjectActivity(id); const deliveries=listDeliveries(id); const issues=listProjectIssues(id); const photos=listProjectPhotos(id);
  const openIssues=issues.filter((issue)=>!["Resolved","Closed"].includes(issue.status)).length; const today=appToday(); const nextDelivery=[...deliveries].filter((delivery)=>["Planned","Confirmed"].includes(delivery.status)&&delivery.deliveryDate>=today).sort((a,b)=>`${a.deliveryDate} ${a.deliveryTime}`.localeCompare(`${b.deliveryDate} ${b.deliveryTime}`))[0];
  return <PortalShell active="/portal/projects">
    <PortalTopbar eyebrow={`${project.location} · ${project.client}`} title={project.name} action={<>{canEdit&&<Link className="os-secondary-action" href={`/portal/projects/${id}/edit`}>{t("Edit")} {t("Project").toLowerCase()}</Link>}<StatusBadge status={project.status} label={t(project.status)}/></>}/>
    <div className="os-project-tabs"><a className="active" href="#overview">{t("Overview")}</a><Link href={`/portal/projects/${id}/elements`}>{t("Element register")}</Link><a href="#deliveries">{t("Deliveries")}</a><a href="#issues">{t("Issues")}</a><a href="#people">{t("Team")}</a><a href="#photos">{t("Photos")}</a><a href="#documents">{t("Documents")}</a><a href="#reports">{t("Reports")}</a><a href="#history">{t("History")}</a></div>
    <section className="os-project-summary" id="overview"><div><span>{t("Schedule")}</span><strong>{project.startDate||t("Start not set")} → {project.targetDate||t("Target not set")}</strong></div><div><span>{t("Responsible manager")}</span><strong>{project.manager}</strong></div><div><span>{t("Project notes")}</span><p>{project.description||t("No project notes yet.")}</p></div></section>
    <section className="os-metrics-grid os-metrics-compact"><MetricCard value={`${project.progress}%`} label={t("Progress")} note={t("Overall project")}/><MetricCard value={members.length} label={t("Project members")} note={`${members.filter(member=>member.status==="On site").length} ${t("On site").toLowerCase()}`}/><MetricCard value={nextDelivery?`${nextDelivery.deliveryDate} ${nextDelivery.deliveryTime}`:"—"} label={t("Next delivery")} note={nextDelivery?.loadRef||t("No planned load")}/><MetricCard value={openIssues} label={t("Open issues")} note={`${issues.length} ${t("total records")}`}/></section>
    <section className="os-workspace-grid">
      <article className="os-panel os-workspace-full" id="deliveries"><div className="os-panel-head"><div><p>{t("Logistics").toUpperCase()}</p><h2>{t("Deliveries")}</h2></div>{canOperate&&<details className="os-inline-editor"><summary>+ {t("Add delivery")}</summary><DeliveryForm projectId={id} t={t}/></details>}</div><div className="os-record-list">{deliveries.map(delivery=><div className="os-record" key={delivery.id}><div><StatusBadge status={delivery.status} label={t(delivery.status)}/><strong>{delivery.loadRef||t("Unnumbered load")} · {delivery.description}</strong><span>{delivery.deliveryDate} {delivery.deliveryTime} · {delivery.supplier}</span>{delivery.notes&&<small>{delivery.notes}</small>}</div>{canOperate&&<details className="os-inline-editor"><summary>{t("Edit")}</summary><DeliveryForm projectId={id} delivery={delivery} t={t}/>{canEdit&&["Planned","Cancelled"].includes(delivery.status)&&<form action={deleteDeliveryAction} className="os-danger-form"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="id" value={delivery.id}/><button type="submit">{t("Delete delivery")}</button></form>}</details>}</div>)}</div></article>
      <article className="os-panel os-workspace-full" id="issues"><div className="os-panel-head"><div><p>{t("Control").toUpperCase()}</p><h2>{t("Issues & defects")}</h2></div>{canOperate&&<details className="os-inline-editor"><summary>+ {t("Add issue")}</summary><IssueForm projectId={id} employees={members} t={t}/></details>}</div><div className="os-record-list">{issues.map(issue=><div className="os-record" key={issue.id}><div><StatusBadge status={issue.status} label={t(issue.status)}/><strong>{issue.title}</strong><span>{t(issue.priority)} · {issue.category} · {issue.owner||t("Unassigned")}</span>{issue.details&&<small>{issue.details}</small>}</div>{canOperate&&<details className="os-inline-editor"><summary>{t("Edit / resolve")}</summary><IssueForm projectId={id} issue={issue} employees={members} t={t}/>{canEdit&&issue.status==="Open"&&<form action={deleteIssueAction} className="os-danger-form"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="id" value={issue.id}/><button type="submit">{t("Delete issue")}</button></form>}</details>}</div>)}</div></article>
      <article className="os-panel" id="people"><div className="os-panel-head"><div><p>{t("Team").toUpperCase()}</p><h2>{t("Project members")}</h2></div><Link href="/portal/employees">{t("Register")} →</Link></div><div className="os-member-list">{members.map(member=><div key={member.id}><section><strong>{member.name}</strong><span>{t(member.projectRole)} · {t(member.role)}</span></section>{canEdit&&<div className="os-member-actions"><details><summary>{t("Edit role")}</summary><form action={updateMemberRoleAction}><input type="hidden" name="projectId" value={id}/><input type="hidden" name="employeeId" value={member.id}/><input name="projectRole" maxLength={80} defaultValue={member.projectRole} required/><button type="submit">{t("Save role")}</button></form></details>{project.managerEmployeeId!==member.id&&<form action={removeMemberAction}><input type="hidden" name="projectId" value={id}/><input type="hidden" name="employeeId" value={member.id}/><button type="submit">{t("Remove")}</button></form>}</div>}</div>)}</div>{canEdit&&available.length>0&&<form action={assignMemberAction} className="os-compact-form"><input type="hidden" name="projectId" value={id}/><select name="employeeId" required defaultValue=""><option value="" disabled>{t("Select employee")}</option>{available.map(employee=><option value={employee.id} key={employee.id}>{employee.name} · {t(employee.role)}</option>)}</select><input name="projectRole" maxLength={80} placeholder={t("Project role")} required/><button className="os-primary-action" type="submit">{t("Assign")}</button></form>}</article>
      <ProjectPhotosSection projectId={id} photos={photos} canUpload={canOperate} canDelete={canEdit}/>
      <ProjectDocumentsSection projectId={id} documents={projectDocuments} legacy={legacyDocuments} canUpload={canOperate} canDelete={canEdit}/>
      <article className="os-panel" id="reports"><div className="os-panel-head"><div><p>{t("Reporting").toUpperCase()}</p><h2>{t("Daily reports")}</h2></div>{canOperate&&<Link href="/portal/reports/new">+ {t("Report")}</Link>}</div><div className="os-doc-list">{reports.map(report=><div key={report.id}><span>{report.date}</span><section><strong>{report.work}</strong><small>{report.people} {t("people")} · {report.author}</small></section></div>)}</div></article>
      <article className="os-panel os-workspace-full" id="history"><div className="os-panel-head"><div><p>{t("History").toUpperCase()}</p><h2>{t("Project history")}</h2></div><span className="os-muted">{activity.length} {t("events")}</span></div><div className="os-event-feed">{activity.map(event=><div className="os-event-row" key={event.id}><time>{formatAppDate(event.createdAt)}<small>{formatAppTime(event.createdAt)}</small></time><span className="os-event-type">{t("Activity")}</span><section><strong>{event.action}</strong>{event.details&&<p>{event.details}</p>}<small>{event.actor}</small></section></div>)}</div></article>
    </section>
  </PortalShell>;
}

type DeliveryData={id:number;deliveryDate:string;deliveryTime:string;supplier:string;loadRef:string;description:string;status:string;notes:string};
function DeliveryForm({projectId,delivery,t}:{projectId:string;delivery?:DeliveryData;t:(value:string)=>string}){return <form action={saveDeliveryAction} className="os-mini-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="id" value={delivery?.id}/><label>{t("Date")}<input type="date" name="deliveryDate" defaultValue={delivery?.deliveryDate??appToday()} required/></label><label>{t("Time")}<input type="time" name="deliveryTime" defaultValue={delivery?.deliveryTime}/></label><label>{t("Supplier")}<input name="supplier" maxLength={160} defaultValue={delivery?.supplier} required/></label><label>{t("Load reference")}<input name="loadRef" maxLength={80} defaultValue={delivery?.loadRef}/></label><label className="wide">{t("Description")}<input name="description" maxLength={500} defaultValue={delivery?.description} required/></label><label>{t("Status")}<select name="status" defaultValue={delivery?.status??"Planned"}>{deliveryStatuses.map(status=><option value={status} key={status}>{t(status)}</option>)}</select></label><label className="wide">{t("Notes")}<textarea name="notes" maxLength={2000} defaultValue={delivery?.notes}/></label><button className="os-primary-action" type="submit">{t("Save delivery")}</button></form>}
type IssueData={id:number;createdDate:string;category:string;title:string;priority:string;status:string;owner:string;ownerEmployeeId:string|null;details:string};
function IssueForm({projectId,issue,employees,t}:{projectId:string;issue?:IssueData;employees:{id:string;name:string}[];t:(value:string)=>string}){return <form action={saveIssueAction} className="os-mini-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="id" value={issue?.id}/><label>{t("Date")}<input type="date" name="createdDate" defaultValue={issue?.createdDate??appToday()} required/></label><label>{t("Category")}<input name="category" maxLength={100} defaultValue={issue?.category} required/></label><label className="wide">{t("Title")}<input name="title" maxLength={240} defaultValue={issue?.title} required/></label><label>{t("Priority")}<select name="priority" defaultValue={issue?.priority??"Normal"}>{priorities.map(priority=><option value={priority} key={priority}>{t(priority)}</option>)}</select></label><label>{t("Status")}<select name="status" defaultValue={issue?.status??"Open"}>{issueStatuses.map(status=><option value={status} key={status}>{t(status)}</option>)}</select></label><label>{t("Responsible")}<select name="ownerEmployeeId" defaultValue={issue?.ownerEmployeeId??""}><option value="">{t("Unassigned")}</option>{employees.map(employee=><option value={employee.id} key={employee.id}>{employee.name}</option>)}</select></label><label className="wide">{t("Details")}<textarea name="details" maxLength={3000} defaultValue={issue?.details}/></label><button className="os-primary-action" type="submit">{t("Save issue")}</button></form>}
