import Link from "next/link";
import { notFound } from "next/navigation";
import { MetricCard } from "../../../../components/portal/MetricCard";
import { PortalShell, PortalTopbar, StatusBadge } from "../../../../components/portal/PortalShell";
import { requireUser } from "../../../../lib/auth";
import { canManageProjectOperations, canManageProjects } from "../../../../lib/permissions";
import { getProject, listDeliveries, listDocuments, listEmployees, listProjectActivity, listProjectIssues, listProjectMembers, listProjectPhotos, listReports } from "../../../../lib/repositories";
import { assignMemberAction, deleteDeliveryAction, deleteIssueAction, removeMemberAction, saveDeliveryAction, saveIssueAction, updateMemberRoleAction } from "../actions";

const deliveryStatuses=["Planned","Confirmed","Received","Cancelled"];
const issueStatuses=["Open","In progress","Resolved","Closed"];
const priorities=["Low","Normal","High","Critical"];

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const project=getProject(id); if(!project)notFound();
  const user=await requireUser(); const canEdit=canManageProjects(user); const canOperate=canManageProjectOperations(user);
  const allEmployees=listEmployees(); const members=listProjectMembers(id); const memberIds=new Set(members.map((member)=>member.id)); const available=allEmployees.filter((employee)=>!memberIds.has(employee.id));
  const projectDocs=listDocuments().filter((document)=>document.project===project.name||document.project==="All projects"); const reports=listReports().filter((report)=>report.projectId===id); const activity=listProjectActivity(id); const deliveries=listDeliveries(id); const issues=listProjectIssues(id); const photos=listProjectPhotos(id);
  const openIssues=issues.filter((issue)=>!["Resolved","Closed"].includes(issue.status)).length; const today=new Date().toISOString().slice(0,10); const nextDelivery=[...deliveries].filter((delivery)=>["Planned","Confirmed"].includes(delivery.status)&&delivery.deliveryDate>=today).sort((a,b)=>`${a.deliveryDate} ${a.deliveryTime}`.localeCompare(`${b.deliveryDate} ${b.deliveryTime}`))[0];
  return <PortalShell active="/portal/projects">
    <PortalTopbar eyebrow={`${project.location} · ${project.client}`} title={project.name} action={<>{canEdit&&<Link className="os-secondary-action" href={`/portal/projects/${id}/edit`}>Edit project</Link>}<StatusBadge status={project.status}/></>}/>
    <div className="os-project-tabs"><a className="active" href="#overview">Overview</a><a href="#deliveries">Deliveries</a><a href="#issues">Issues</a><a href="#people">People</a><a href="#photos">Photos</a><a href="#documents">Documents</a><a href="#reports">Reports</a><a href="#history">History</a></div>
    <section className="os-project-summary" id="overview"><div><span>Schedule</span><strong>{project.startDate||"Start not set"} → {project.targetDate||"Target not set"}</strong></div><div><span>Responsible manager</span><strong>{project.manager}</strong></div><div><span>Project notes</span><p>{project.description||"No project notes yet."}</p></div></section>
    <section className="os-metrics-grid os-metrics-compact"><MetricCard value={`${project.progress}%`} label="Progress" note="Overall project"/><MetricCard value={members.length} label="Project members" note={`${members.filter((member)=>member.status==="On site").length} on site`}/><MetricCard value={nextDelivery?`${nextDelivery.deliveryDate} ${nextDelivery.deliveryTime}`:"—"} label="Next delivery" note={nextDelivery?.loadRef||"No planned load"}/><MetricCard value={openIssues} label="Open issues" note={`${issues.length} total records`}/></section>
    <section className="os-workspace-grid">
      <article className="os-panel os-workspace-full" id="deliveries"><div className="os-panel-head"><div><p>LOGISTICS</p><h2>Deliveries</h2></div>{canOperate&&<details className="os-inline-editor"><summary>+ Add delivery</summary><DeliveryForm projectId={id}/></details>}</div><div className="os-record-list">{deliveries.map((delivery)=><div className="os-record" key={delivery.id}><div><StatusBadge status={delivery.status}/><strong>{delivery.loadRef||"Unnumbered load"} · {delivery.description}</strong><span>{delivery.deliveryDate} {delivery.deliveryTime} · {delivery.supplier}</span>{delivery.notes&&<small>{delivery.notes}</small>}</div>{canOperate&&<details className="os-inline-editor"><summary>Edit</summary><DeliveryForm projectId={id} delivery={delivery}/>{canEdit&&["Planned","Cancelled"].includes(delivery.status)&&<form action={deleteDeliveryAction} className="os-danger-form"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="id" value={delivery.id}/><button type="submit">Delete delivery</button></form>}</details>}</div>)}</div></article>
      <article className="os-panel os-workspace-full" id="issues"><div className="os-panel-head"><div><p>CONTROL</p><h2>Issues & defects</h2></div>{canOperate&&<details className="os-inline-editor"><summary>+ Add issue</summary><IssueForm projectId={id} employees={members}/></details>}</div><div className="os-record-list">{issues.map((issue)=><div className="os-record" key={issue.id}><div><StatusBadge status={issue.status}/><strong>{issue.title}</strong><span>{issue.priority} · {issue.category} · {issue.owner||"Unassigned"}</span>{issue.details&&<small>{issue.details}</small>}</div>{canOperate&&<details className="os-inline-editor"><summary>Edit / resolve</summary><IssueForm projectId={id} issue={issue} employees={members}/>{canEdit&&issue.status==="Open"&&<form action={deleteIssueAction} className="os-danger-form"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="id" value={issue.id}/><button type="submit">Delete issue</button></form>}</details>}</div>)}</div></article>
      <article className="os-panel" id="people"><div className="os-panel-head"><div><p>TEAM</p><h2>Project members</h2></div><Link href="/portal/employees">Register →</Link></div><div className="os-member-list">{members.map((member)=><div key={member.id}><section><strong>{member.name}</strong><span>{member.projectRole} · {member.role}</span></section>{canEdit&&<div className="os-member-actions"><details><summary>Edit role</summary><form action={updateMemberRoleAction}><input type="hidden" name="projectId" value={id}/><input type="hidden" name="employeeId" value={member.id}/><input name="projectRole" maxLength={80} defaultValue={member.projectRole} required/><button type="submit">Save role</button></form></details>{project.managerEmployeeId!==member.id&&<form action={removeMemberAction}><input type="hidden" name="projectId" value={id}/><input type="hidden" name="employeeId" value={member.id}/><button type="submit">Remove</button></form>}</div>}</div>)}</div>{canEdit&&available.length>0&&<form action={assignMemberAction} className="os-compact-form"><input type="hidden" name="projectId" value={id}/><select name="employeeId" required defaultValue=""><option value="" disabled>Select employee</option>{available.map((employee)=><option value={employee.id} key={employee.id}>{employee.name} · {employee.role}</option>)}</select><input name="projectRole" maxLength={80} placeholder="Project role" required/><button className="os-primary-action" type="submit">Assign</button></form>}</article>
      <article className="os-panel" id="photos"><div className="os-panel-head"><div><p>PHOTO LOG</p><h2>Site photos</h2></div><span className="os-muted">{photos.length} records</span></div><div className="os-doc-list">{photos.map((photo)=><div key={photo.id}><span>{photo.photoDate}</span><section><strong>{photo.caption}</strong><small>{photo.area} · {photo.author}</small></section></div>)}</div></article>
      <article className="os-panel" id="documents"><div className="os-panel-head"><div><p>DOCUMENTS</p><h2>Current set</h2></div><Link href="/portal/documents">View all →</Link></div><div className="os-doc-list">{projectDocs.map((document)=><div key={document.id}><span>{document.category}</span><section><strong>{document.name}</strong><small>{document.revision} · {document.status}</small></section></div>)}</div></article>
      <article className="os-panel" id="reports"><div className="os-panel-head"><div><p>REPORTING</p><h2>Daily reports</h2></div><Link href="/portal/reports/new">+ Report</Link></div><div className="os-doc-list">{reports.map((report)=><div key={report.id}><span>{report.date}</span><section><strong>{report.work}</strong><small>{report.people} people · {report.author}</small></section></div>)}</div></article>
      <article className="os-panel os-workspace-full" id="history"><div className="os-panel-head"><div><p>TIMELINE</p><h2>Project history</h2></div><span className="os-muted">{activity.length} events</span></div><div className="os-event-feed">{activity.map((event)=><div className="os-event-row" key={event.id}><time>{event.createdAt.slice(0,10)}<small>{event.createdAt.slice(11,16)}</small></time><span className="os-event-type">Activity</span><section><strong>{event.action}</strong>{event.details&&<p>{event.details}</p>}<small>{event.actor}</small></section></div>)}</div></article>
    </section>
  </PortalShell>;
}

type DeliveryData={id:number;deliveryDate:string;deliveryTime:string;supplier:string;loadRef:string;description:string;status:string;notes:string};
function DeliveryForm({projectId,delivery}:{projectId:string;delivery?:DeliveryData}){return <form action={saveDeliveryAction} className="os-mini-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="id" value={delivery?.id}/><label>Date<input type="date" name="deliveryDate" defaultValue={delivery?.deliveryDate??new Date().toISOString().slice(0,10)} required/></label><label>Time<input type="time" name="deliveryTime" defaultValue={delivery?.deliveryTime}/></label><label>Supplier<input name="supplier" maxLength={160} defaultValue={delivery?.supplier} required/></label><label>Load reference<input name="loadRef" maxLength={80} defaultValue={delivery?.loadRef}/></label><label className="wide">Description<input name="description" maxLength={500} defaultValue={delivery?.description} required/></label><label>Status<select name="status" defaultValue={delivery?.status??"Planned"}>{deliveryStatuses.map((status)=><option key={status}>{status}</option>)}</select></label><label className="wide">Notes<textarea name="notes" maxLength={2000} defaultValue={delivery?.notes}/></label><button className="os-primary-action" type="submit">Save delivery</button></form>}
type IssueData={id:number;createdDate:string;category:string;title:string;priority:string;status:string;owner:string;ownerEmployeeId:string|null;details:string};
function IssueForm({projectId,issue,employees}:{projectId:string;issue?:IssueData;employees:{id:string;name:string}[]}){return <form action={saveIssueAction} className="os-mini-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="id" value={issue?.id}/><label>Date<input type="date" name="createdDate" defaultValue={issue?.createdDate??new Date().toISOString().slice(0,10)} required/></label><label>Category<input name="category" maxLength={100} defaultValue={issue?.category} required/></label><label className="wide">Title<input name="title" maxLength={240} defaultValue={issue?.title} required/></label><label>Priority<select name="priority" defaultValue={issue?.priority??"Normal"}>{priorities.map((priority)=><option key={priority}>{priority}</option>)}</select></label><label>Status<select name="status" defaultValue={issue?.status??"Open"}>{issueStatuses.map((status)=><option key={status}>{status}</option>)}</select></label><label>Responsible<select name="ownerEmployeeId" defaultValue={issue?.ownerEmployeeId??""}><option value="">Unassigned</option>{employees.map((employee)=><option value={employee.id} key={employee.id}>{employee.name}</option>)}</select></label><label className="wide">Details<textarea name="details" maxLength={3000} defaultValue={issue?.details}/></label><button className="os-primary-action" type="submit">Save issue</button></form>}
