"use server";
import {redirect} from "next/navigation";
import {revalidatePath} from "next/cache";
import {requireUser} from "../../../../lib/auth";
import {addProjectEvent,approveDailyReport,deleteDraftReport,finalizeReportElements,getEmployee,getProject,getReport,getTimesheetPeriod,getUserEmployeeId,listAttendanceForReport,listProjectWorkforce,logActivity,replaceReportWeather,runTransaction,saveDailyReport,syncReportElements,type AttendanceInput} from "../../../../lib/repositories";
import {canAccessProject,canManageProjectOperations,canReviewDailyReports} from "../../../../lib/permissions";
import {attendanceStatuses} from "../../../../lib/workforce";
import {isTimesheetPeriodEditable} from "../../../../lib/timesheet-policy";
import {parseReportWeatherSnapshot} from "../../../../lib/weather";
import {captureReportFormValues,type ReportFormValues} from "../../../../lib/report-form-state";
export type ReportActionState={error:string;values?:ReportFormValues};export type ApprovalActionState={error:string};
const clean=(data:FormData,key:string,max=4000)=>String(data.get(key)??"").trim().slice(0,max);

export async function saveDailyReportAction(_:ReportActionState,data:FormData):Promise<ReportActionState>{
 const fail=(error:string):ReportActionState=>({error,values:captureReportFormValues(data)});const user=await requireUser();if(!canManageProjectOperations(user))return fail("You do not have permission to create daily reports.");
 const projectId=clean(data,"projectId",100),project=getProject(projectId),date=clean(data,"date",10),intent=clean(data,"intent",20),reportId=Number(clean(data,"reportId",20)||0),existing=reportId?getReport(reportId):undefined;
 if(!project||!/^\d{4}-\d{2}-\d{2}$/.test(date))return fail("Project and date are required.");if(!canAccessProject(user,projectId))return fail("You do not have access to this project.");if(existing&&(existing.projectId!==projectId||(!canReviewDailyReports(user)&&(existing.reporterUserId!==user.id||existing.status!=="Draft"))))return fail("You cannot edit this report.");if(!isTimesheetPeriodEditable(getTimesheetPeriod(date.slice(0,7)).status))return fail("This month is closed and cannot be changed.");
 const workforce=listProjectWorkforce(projectId),attendance:AttendanceInput[]=[];for(const employee of workforce){if(data.get(`include_${employee.id}`)!=="on")continue;const attendanceStatus=clean(data,`status_${employee.id}`,50);if(!attendanceStatuses.includes(attendanceStatus as typeof attendanceStatuses[number]))return fail("Invalid attendance status.");let regularHours=Number(data.get(`regular_${employee.id}`)??0),overtimeHours=Number(data.get(`overtime_${employee.id}`)??0);if(!Number.isFinite(regularHours)||!Number.isFinite(overtimeHours)||regularHours<0||overtimeHours<0||regularHours+overtimeHours>24)return fail("Hours must be between 0 and 24.");if(attendanceStatus!=="Worked"){regularHours=0;overtimeHours=0;}if(!getEmployee(employee.id))return fail("Attendance employee is invalid.");attendance.push({employeeId:employee.id,status:attendanceStatus,regularHours,overtimeHours,comment:clean(data,`comment_${employee.id}`,500)});}
 const status=intent==="submit"?"Submitted":"Draft",work=clean(data,"work"),elementIds=data.getAll("elementIds").map(Number);if(status==="Submitted"&&!work)return fail("General work performed is required before submission.");if(elementIds.some((id)=>!Number.isInteger(id)||id<=0))return fail("Invalid element selection.");const snapshot=parseReportWeatherSnapshot(clean(data,"weatherSnapshot",12000));
 let savedId=0;try{runTransaction(()=>{const previousAttendance=existing?listAttendanceForReport(existing.id):[];savedId=saveDailyReport({id:existing?.id,projectId,project:project.name,date,work,weather:clean(data,"weather",500),materials:clean(data,"materials"),equipment:clean(data,"equipment"),problems:clean(data,"problems"),safety:clean(data,"safety"),additionalNotes:clean(data,"additionalNotes"),author:existing?.author??user.name,reporterUserId:existing?.reporterUserId??user.id,reporterEmployeeId:existing?.reporterEmployeeId??getUserEmployeeId(user.id),status,attendance});syncReportElements(savedId,projectId,elementIds);if((!existing||existing.status==="Draft")&&snapshot.length)replaceReportWeather(savedId,snapshot);logActivity({userId:user.id,actor:user.name,action:existing?"Updated daily report":"Created daily report",entityType:"project",entityId:projectId,details:`${project.name} · ${date} · ${status}`});if(status==="Submitted"&&existing?.status!=="Submitted"){addProjectEvent({projectId,date,time:"",type:"Report",title:"Daily report submitted",details:work,author:user.name});logActivity({userId:user.id,actor:user.name,action:"Submitted daily report",entityType:"project",entityId:projectId,details:`Report #${savedId}`});}if(existing&&JSON.stringify(previousAttendance.map(({employeeId,status:oldStatus,regularHours,overtimeHours,comment})=>({employeeId,status:oldStatus,regularHours,overtimeHours,comment})))!==JSON.stringify(attendance))logActivity({userId:user.id,actor:user.name,action:"Corrected attendance",entityType:"project",entityId:projectId,details:`Report #${savedId}`});});}catch(error){return fail(error instanceof Error?error.message:"Unable to save Daily Report.");}
 revalidatePath("/portal/reports");revalidatePath(`/portal/reports/${savedId}`);redirect(status==="Submitted"?`/portal/reports?success=submitted&report=${savedId}`:`/portal/reports/${savedId}?success=draft`);
}
export async function approveDailyReportAction(_:ApprovalActionState,data:FormData):Promise<ApprovalActionState>{const user=await requireUser();if(!canReviewDailyReports(user))return{error:"You do not have permission to approve this report."};const id=Number(data.get("reportId")),report=getReport(id);if(!report||!canAccessProject(user,report.projectId))return{error:"Daily Report not found."};if(getTimesheetPeriod(report.date.slice(0,7)).status==="Closed")return{error:"This month is closed and cannot be changed."};try{runTransaction(()=>{const result=approveDailyReport(id,user.id);if(!result.changes)throw new Error("Only a submitted report can be approved.");finalizeReportElements(id,report.date,user);addProjectEvent({projectId:report.projectId,date:report.date,time:"",type:"Report",title:"Daily report approved",details:`Report #${id}`,author:user.name});logActivity({userId:user.id,actor:user.name,action:"Approved daily report",entityType:"project",entityId:report.projectId,details:`Report #${id}`});});}catch(error){return{error:error instanceof Error?error.message:"Report approval failed."};}revalidatePath("/portal/reports");revalidatePath(`/portal/reports/${id}`);revalidatePath(`/portal/projects/${report.projectId}/elements`);redirect(`/portal/reports?success=approved&report=${id}`);}
export async function deleteDraftReportAction(data:FormData){const user=await requireUser(),id=Number(data.get("reportId")),report=getReport(id);if(!report||report.status!=="Draft"||!canAccessProject(user,report.projectId)||(!canReviewDailyReports(user)&&!(canManageProjectOperations(user)&&report.reporterUserId===user.id)))throw new Error("Draft report deletion is not permitted.");runTransaction(()=>{const result=deleteDraftReport(id);if(result.changes!==1)throw new Error("Only Draft reports can be deleted.");logActivity({userId:user.id,actor:user.name,action:"Deleted draft Daily Report",entityType:"project",entityId:report.projectId,details:`Report #${id} · ${report.date}`});});revalidatePath("/portal/reports");revalidatePath(`/portal/projects/${report.projectId}/elements`);redirect("/portal/reports?success=deleted");}
