import Link from "next/link";import {PortalShell,PortalTopbar} from "../../../../components/portal/PortalShell";import {BackLink} from "../../../../components/portal/BackLink";import {DailyReportForm} from "../../../../components/portal/DailyReportForm";import {listProjects,listProjectElements,listProjectWorkforce} from "../../../../lib/repositories";import {saveDailyReportAction} from "./actions";import {appToday} from "../../../../lib/datetime";import {requireUser} from "../../../../lib/auth";import {canAccessProject,canManageProjectOperations} from "../../../../lib/permissions";import {getPortalLanguage} from "../../../../lib/portal-locale";import {portalText} from "../../../../data/portal-i18n";
export default async function NewReportPage({searchParams}:{searchParams:Promise<{project?:string}>}){const user=await requireUser(),language=await getPortalLanguage(),t=(v:string)=>portalText(language,v),params=await searchParams;if(!canManageProjectOperations(user))return <PortalShell active="/portal/reports"><PortalTopbar eyebrow={t("Site reporting")} title={t("New daily report")}/><section className="os-panel"><h2>{t("Restricted")}</h2><p>{t("Your role does not allow official Daily Report creation.")}</p><Link href="/portal/reports">{t("View daily reports")}</Link></section></PortalShell>;
  // Launched from a project → bind the form to that project only (no reselection).
  let projects=listProjects().filter((project)=>project.status==="Active"&&!project.archivedAt&&canAccessProject(user,project.id)&&canManageProjectOperations(user));
  const fromProject=params.project?projects.find((project)=>project.id===params.project):undefined;
  if(fromProject)projects=[fromProject];
  const crews=projects.map((project)=>({project:{...project},employees:listProjectWorkforce(project.id).map((employee)=>({...employee,certificates:[...employee.certificates]})),elements:listProjectElements(project.id,{available:true}).map((element)=>({...element}))}));
  return <PortalShell active="/portal/projects"><BackLink href={fromProject?`/portal/projects/${fromProject.id}#reports`:"/portal/reports"} label={fromProject?t("Back to project"):t("Back to daily reports")}/><PortalTopbar eyebrow={`${t("Site reporting")} · ${t("Fast site workflow")}`} title={t("New daily report")}/>{crews.length?<DailyReportForm action={saveDailyReportAction} crews={crews} language={language} today={appToday()}/>:<p className="os-empty-state">{t("No accessible active projects.")}</p>}</PortalShell>;
}
