"use client";
import {useActionState,useState} from "react";
import {portalText,type PortalLanguage} from "../../data/portal-i18n";
import {syncFields,type SyncField,type ValidationIssue} from "../../lib/element-sync";
import {elementTypes} from "../../lib/elements";
import type {SyncActionState} from "../../app/portal/projects/[id]/elements/sync/actions";

const fieldLabels:Record<SyncField,string>={code:"Element code / mark",elementType:"Element type",floor:"Floor / level",zone:"Zone / section",drawingRef:"Drawing / reference",description:"Description",weight:"Weight",length:"Length",width:"Width",height:"Height",supplier:"Supplier",plannedDeliveryDate:"Planned delivery date"};
const issueLabels:Record<string,string>={required_mapping:"Required field is not mapped. Select the XLSX column manually.",missing_code:"Element code is missing.",duplicate_code:"Duplicate element code.",invalid_type:"Unknown element type.",invalid_number:"Dimensions and weight must be non-negative numbers.",invalid_date:"Planned delivery date must use YYYY-MM-DD."};

export function ElementSync({projectId,action,applyAction,language,initialState}:{projectId:string;action:(state:SyncActionState,data:FormData)=>Promise<SyncActionState>;applyAction:(data:FormData)=>void|Promise<void>;language:PortalLanguage;initialState?:SyncActionState}){
  const[state,formAction,pending]=useActionState(action,initialState??{error:""}),[fileName,setFileName]=useState(""),t=(v:string)=>portalText(language,v),mapping=state.mapping;
  return <div className="os-sync-workspace">
    {!state.diff&&<form action={formAction} className="os-form-section">
      <input type="hidden" name="projectId" value={projectId}/>{state.sessionId&&<input type="hidden" name="sessionId" value={state.sessionId}/>}<div><span>XLSX</span><h2>{t("XLSX register synchronization")}</h2></div>
      {!state.sessionId&&<div className="os-form-grid"><label className="os-file-picker"><span>{t("XLSX workbook")}</span><input className="os-visually-hidden" name="file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required onChange={(event)=>setFileName(event.target.files?.[0]?.name??"")}/><span className="os-secondary-action">{t("Choose XLSX file")}</span><small>{fileName||t("No file selected")}</small></label><label>{t("Source revision")}<input name="sourceRevision" maxLength={100}/></label><label>{t("Import notes")}<input name="notes" maxLength={1000}/></label></div>}
      {!mapping&&<button className="os-primary-action" name="stage" value="inspect" type="submit" disabled={pending}>{pending?t("Parsing workbook…"):t("Load workbook")}</button>}
      {mapping&&<>
        <div className="os-form-grid"><label>{t("Worksheet")}<select name="worksheet" defaultValue={mapping.worksheet}>{state.worksheets?.map((name)=><option key={name} value={name}>{name}</option>)}</select></label><label>{t("Header row")}<input name="headerRow" type="number" min="1" max="10000" defaultValue={mapping.headerRow} list="header-row-options"/><datalist id="header-row-options">{mapping.headerCandidates.map((row)=><option key={row} value={row}/>)}</datalist></label><button className="os-secondary-action" name="stage" value="inspect" type="submit" disabled={pending}>{t("Refresh columns")}</button></div>
        <section className="os-mapping-grid"><div className="os-panel-head"><h2>{t("Column mapping")}</h2><span>{mapping.columns.length} {t("detected columns")}</span></div>{syncFields.map((field)=><MappingField key={`${field}-${mapping.worksheet}-${mapping.headerRow}-${mapping.selected[field]??"none"}`} field={field} state={state} t={t}/>)}</section>
        <button className="os-primary-action" name="stage" value="preview" type="submit" disabled={pending}>{pending?t("Parsing workbook…"):t("Preview synchronization")}</button>
      </>}
      {state.error&&<p className="os-form-error" role="alert">{t(state.error)}</p>}
      {!!state.validation?.length&&<ValidationPanel errors={state.validation} summary={state.validationSummary??[]} t={t}/>}
      {(!!state.unknownTypes?.length||!!state.duplicates?.length)&&<GroupedImportIssues state={state} t={t}/>}
    </form>}
    {state.diff&&state.sessionId&&<form action={applyAction} className="os-sync-preview"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="importId" value={state.sessionId}/><section className="os-metrics-grid os-metrics-compact">{[["New",state.diff.newRows.length],["Changed",state.diff.changed.length],["Unchanged",state.diff.unchanged.length],["Missing from latest revision",state.diff.missing.length],["Conflicts",state.diff.conflicts.length],["Installed and preserved",state.diff.installedAffected]].map(([label,count])=><article className="os-metric-card" key={String(label)}><span>{t(String(label))}</span><strong>{count}</strong></article>)}</section>{state.duplicate&&<p className="os-sync-warning" role="status">{t("This exact source file has already been applied. Continue to the existing result.")}</p>}<DiffGroup title={t("New elements")} rows={state.diff.newRows.map((row,index)=><strong key={`${row.code}-${row.row??index}`}>{row.code}</strong>)}/><DiffGroup title={t("Changed elements")} rows={state.diff.changed.map(({existing,incoming,changes})=><article key={`${existing.id}-${incoming.row}`}><strong>{existing.code}{existing.status==="Installed"?` · ${t("Installed — operational history will be preserved.")}`:""}</strong>{changes.map((change)=><p key={change.field}>{t(fieldLabels[change.field])}: <del>{String(change.oldValue??"—")}</del> → <ins>{String(change.newValue??"—")}</ins></p>)}</article>)}/><DiffGroup title={t("Missing from latest revision / Requires review")} rows={state.diff.missing.map((row)=><label key={row.id}><strong>{row.code}</strong><select name={`missing_${row.id}`} defaultValue="Keep"><option value="Keep">{t("Keep active")}</option>{row.status!=="Installed"&&<option value="Supersede">{t("Mark superseded / removed from design")}</option>}</select></label>)}/><DiffGroup title={t("Potential rename conflicts")} rows={state.diff.conflicts.map(({incoming,potential})=><label key={`${incoming.code}-${incoming.row}`}><strong>{incoming.code} ↔ {potential.map((row)=>`${row.code} (#${row.id})`).join(", ")}</strong><select name={`conflict_${incoming.row}`} defaultValue="Ignore"><option value="Ignore">{t("Ignore incoming row")}</option><option value="New">{t("Create as new independent element")}</option></select></label>)}/><button className="os-primary-action" type="submit">{t(state.duplicate?"View applied synchronization result":"Apply synchronization")}</button></form>}
  </div>;
}

function MappingField({field,state,t}:{field:SyncField;state:SyncActionState;t:(value:string)=>string}){const mapping=state.mapping!,automatic=mapping.automatic[field],selected=mapping.selected[field],column=mapping.columns.find((item)=>item.key===selected),required=field==="code"||field==="elementType",missing=required&&!selected,defaultValue=selected?(selected===automatic?"__auto__":selected):(automatic?"__skip__":"__auto__");return <label className={`os-mapping-field${missing?" os-mapping-missing":""}`}><strong>{t(fieldLabels[field])}{required?" *":""}</strong><select name={`map_${field}`} defaultValue={defaultValue} aria-invalid={missing}><option value="__auto__">{t("Automatic")}{automatic?` → ${mapping.columns.find((item)=>item.key===automatic)?.label??automatic}`:""}</option><option value="__skip__">{t("Do not import")}</option>{mapping.columns.map((item)=><option key={item.key} value={item.key}>{item.label}</option>)}</select><small>{column?.samples.length?<>{t("Sample")}: {column.samples.join(" · ")}</>:t("No sample values")}</small></label>}
function ValidationPanel({errors,summary,t}:{errors:ValidationIssue[];summary:Array<{code:string;count:number}>;t:(value:string)=>string}){return <section className="os-validation-panel" role="alert"><strong>{t("Validation issues")}: {errors.length} {t("rows")}</strong>{summary.map((item)=><p key={item.code}>{item.count} × {t(issueLabels[item.code]??item.code)}</p>)}<details><summary>{t("Show row details")}</summary><ul>{errors.map((issue,index)=><li key={`${issue.row}-${issue.code}-${index}`}>{issue.row?`${t("Row")} ${issue.row} — `:""}{t(issueLabels[issue.code]??issue.message)}{issue.value?` (${issue.value})`:""}</li>)}</ul></details></section>}
function GroupedImportIssues({state,t}:{state:SyncActionState;t:(value:string)=>string}){const groups=(state.unknownTypes?.length??0)+(state.duplicates?.length??0);return <section className="os-grouped-import-issues" role="alert"><div className="os-panel-head"><h2>{t("Review issues")}: {groups} {t("groups")}</h2><span>{t("Resolve before synchronization")}</span></div>{state.unknownTypes?.map((group)=><article key={`${group.normalizedValue}-${state.typeMappings?.[group.normalizedValue]??"unmapped"}`}><strong>{t("Unknown source type")}: {group.sourceValue}</strong><p>{t("Occurrences")}: {group.occurrences}</p><p>{t("Sample element codes")}: {group.sampleCodes.join(" · ")||"—"}</p><label>{t("Map to")}<select name={`type_${encodeURIComponent(group.normalizedValue)}`} defaultValue={state.typeMappings?.[group.normalizedValue]??""}><option value="">{t("Select canonical type")}</option>{elementTypes.map((type)=><option key={type} value={type}>{t(type)}</option>)}</select></label></article>)}{state.duplicates?.map((group)=><article key={`${group.code}-${state.excludedRows?.join("-")}-${state.acceptedRepeatedCodes?.join("-")}`}><strong>{t("Repeated element mark")}: {group.code}</strong><p>{t("Occurrences")}: {group.rows.length} · {t("Potential legitimate repeated physical elements")}</p><p>{t("Found in rows")}: {group.rows.map((row)=>row.row).join(", ")}</p><details open><summary>{t("View rows")}</summary><div className="os-duplicate-rows">{group.rows.map((row)=><label key={row.row}><span><strong>{t("Row")} {row.row}</strong> · {row.sourceType||"—"} · {row.floor||"—"} · {row.zone||"—"}</span><small>{row.drawingRef||"—"} · {row.dimensions||"—"} · {row.weight||"—"}</small><span><input type="checkbox" name={`exclude_row_${row.row}`} defaultChecked={state.excludedRows?.includes(row.row)}/> {t("Exclude row")}</span></label>)}</div></details><label><input type="checkbox" name={`accept_repeat_${encodeURIComponent(group.code.toLocaleLowerCase())}`} defaultChecked={state.acceptedRepeatedCodes?.includes(group.code.toLocaleLowerCase())}/> {t("Keep all as separate physical elements")}</label></article>)}<button className="os-primary-action" name="stage" value="preview" type="submit">{t("Revalidate and continue")}</button></section>}
function DiffGroup({title,rows}:{title:string;rows:React.ReactNode[]}){if(!rows.length)return null;return <section className="os-panel os-sync-group"><h2>{title}</h2><div>{rows}</div></section>}
