"use client";
import Link from "next/link";
import {useActionState} from "react";
import type {Employee,Project} from "../../lib/repositories";
import type {PortalLanguage} from "../../data/portal-i18n";
import {portalText} from "../../data/portal-i18n";
import type {EmployeeActionState} from "../../app/portal/employees/actions";
import {employeeStatuses,employeeTrades} from "../../lib/workforce";

export function EmployeeForm({action,employee,projects,language}:{action:(state:EmployeeActionState,data:FormData)=>Promise<EmployeeActionState>;employee?:Employee;projects:Project[];language:PortalLanguage}){const[state,formAction]=useActionState(action,{error:""});const t=(value:string)=>portalText(language,value);return <form action={formAction} className="os-report-form"><input type="hidden" name="employeeId" value={employee?.id}/><section className="os-form-section"><div><span>01</span><h2>{t("Employee details")}</h2></div><div className="os-form-grid"><label>{t("First name")}<input name="firstName" maxLength={80} defaultValue={employee?.firstName} required/></label><label>{t("Last name")}<input name="lastName" maxLength={80} defaultValue={employee?.lastName} required/></label><label>{t("Position / trade")}<select name="role" defaultValue={employee?.role??"Precast Installer"}>{employeeTrades.map((role)=><option key={role} value={role}>{t(role)}</option>)}</select></label><label>{t("Employment status")}<select name="status" defaultValue={employee?.status??"Active"}>{employeeStatuses.map((status)=><option key={status} value={status}>{t(status)}</option>)}</select></label><label>{t("Phone")}<input name="phone" maxLength={60} defaultValue={employee?.phone}/></label><label>{t("Email (optional)")}<input name="email" type="email" maxLength={160} defaultValue={employee?.email}/></label><label>{t("Default project")}<select name="defaultProjectId" defaultValue={employee?.defaultProjectId??""}><option value="">{t("No default project")}</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><span/></div></section><section className="os-form-section"><div><span>02</span><h2>{t("Employment period")}</h2></div><div className="os-form-grid"><label>{t("Employment start date")}<input name="employmentStartDate" type="date" defaultValue={employee?.employmentStartDate}/></label><label>{t("Employment end date")}<input name="employmentEndDate" type="date" defaultValue={employee?.employmentEndDate}/></label></div><label>{t("Notes")}<textarea name="notes" maxLength={3000} rows={5} defaultValue={employee?.notes}/></label></section>{state.error&&<p className="os-form-error" role="alert">{t(state.error)}</p>}<div className="os-form-actions"><Link href={employee?`/portal/employees/${employee.id}`:"/portal/employees"}>{t("Cancel")}</Link><button className="os-primary-action os-primary-action-dark" type="submit">{t(employee?"Save employee":"Create employee")} →</button></div></form>}
