import Link from "next/link";
import type { DocumentRow,ProjectDocument,ProjectPhoto } from "../../lib/repositories";
import { deleteDocumentAction,deletePhotoAction,updateDocumentMetadataAction,updatePhotoMetadataAction } from "../../app/portal/projects/media-actions";
import { StatusBadge } from "./PortalShell";
import { DocumentUploadForm,PhotoUploadForm } from "./UploadForms";
import { appToday,formatAppDateTime } from "../../lib/datetime";
import { DestructiveAction } from "./DestructiveAction";
import {getPortalLanguage} from "../../lib/portal-locale";import {portalText} from "../../data/portal-i18n";

const categories=["Drawings","Method statements","DVP / DOP","HSE / Risk assessments","Quality","Delivery documents","Certificates","Contracts / Commercial","Other"];
const size=(bytes:number)=>bytes>=1048576?`${(bytes/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;

export async function ProjectDocumentsSection({projectId,documents,legacy,canUpload,canDelete}:{projectId:string;documents:ProjectDocument[];legacy:DocumentRow[];canUpload:boolean;canDelete:boolean}){const language=await getPortalLanguage();const t=(v:string)=>portalText(language,v);return <article className="os-panel os-workspace-full" id="documents">
  <div className="os-panel-head"><div><p>{t("Documents").toUpperCase()}</p><h2>{t("Project documents")}</h2></div>{canUpload&&<details className="os-inline-editor"><summary>↑ {t("Upload document")}</summary><DocumentUploadForm projectId={projectId} today={appToday()}/></details>}</div>
  <div className="os-media-list">{documents.map((document)=><div key={document.id}><section><Link href={`/portal/files/documents/${document.id}`} target="_blank"><strong>{document.title}</strong></Link><span>{document.category} · {document.revision} · {document.documentDate||"No date"}</span><small>{document.uploadedBy} · {formatAppDateTime(document.uploadedAt)} · {size(document.fileSize)}</small></section><StatusBadge status={document.status}/>{canDelete&&<div className="os-media-actions"><details><summary>Edit</summary><form action={updateDocumentMetadataAction} className="os-mini-form"><input type="hidden" name="id" value={document.id}/><label>Title<input name="title" defaultValue={document.title} required/></label><label>Category<select name="category" defaultValue={document.category}>{categories.map((category)=><option key={category}>{category}</option>)}</select></label><label>Revision<input name="revision" defaultValue={document.revision} required/></label><label>Date<input type="date" name="documentDate" defaultValue={document.documentDate} required/></label><label>Status<select name="status" defaultValue={document.status}><option>Current</option><option>Review</option><option>Archived</option></select></label><label>Notes<textarea name="description" defaultValue={document.description}/></label><button type="submit">Save</button></form></details><DestructiveAction action={deleteDocumentAction} itemType="document" itemLabel={`${document.title} · ${document.revision}`} fields={{id:document.id}}/></div>}</div>)}
  {legacy.map((document)=><div key={document.id}><section><strong>{document.name}</strong><span>{document.category} · {document.revision} · {document.updated}</span><small>Legacy record · file not stored</small></section><StatusBadge status={document.status}/></div>)}</div>
</article>}

export async function ProjectPhotosSection({projectId,photos,canUpload,canDelete}:{projectId:string;photos:ProjectPhoto[];canUpload:boolean;canDelete:boolean}){const language=await getPortalLanguage();const t=(v:string)=>portalText(language,v);const stored=photos.filter((photo)=>photo.storedPath);const legacy=photos.filter((photo)=>!photo.storedPath);return <article className="os-panel os-workspace-full" id="photos">
  <div className="os-panel-head"><div><p>{t("Photo log").toUpperCase()}</p><h2>{t("Site photos")}</h2></div>{canUpload&&<details className="os-inline-editor"><summary>+ {t("Upload photo")}</summary><PhotoUploadForm projectId={projectId} today={appToday()}/></details>}</div>
  {stored.length>0&&<div className="os-photo-grid">{stored.map((photo)=><article key={photo.id}><Link href={`/portal/files/photos/${photo.id}`} target="_blank" aria-label={`Open larger photo: ${photo.caption}`}><div className="os-photo-image" role="img" aria-label={photo.caption} style={{backgroundImage:`url(/portal/files/photos/${photo.id})`}}/></Link><div><strong>{photo.caption}</strong><span>{photo.photoDate} · {photo.area||"Site"}</span><small>{photo.author}{photo.notes?` · ${photo.notes}`:""}</small>{canDelete&&<div className="os-media-actions"><details><summary>Edit</summary><form action={updatePhotoMetadataAction} className="os-mini-form"><input type="hidden" name="id" value={photo.id}/><label>Date<input type="date" name="photoDate" defaultValue={photo.photoDate} required/></label><label>Caption<input name="caption" defaultValue={photo.caption} required/></label><label>Area<input name="area" defaultValue={photo.area}/></label><label>Notes<textarea name="notes" defaultValue={photo.notes}/></label><button type="submit">Save</button></form></details><DestructiveAction action={deletePhotoAction} itemType="photo" itemLabel={photo.originalFilename?`${photo.caption} · ${photo.originalFilename}`:photo.caption} fields={{id:photo.id}}/></div>}</div></article>)}</div>}
  {legacy.length>0&&<div className="os-legacy-media"><strong>{t("Legacy photo records")}</strong>{legacy.map((photo)=><span key={photo.id}>{photo.photoDate} · {photo.caption} · {photo.area}</span>)}</div>}{photos.length===0&&<p className="os-empty">{t("No site photos uploaded.")}</p>}
</article>}
