"use client";
import {useActionState,useState,type FormEvent} from "react";
import {useFormStatus} from "react-dom";
import {uploadReportMediaAction,type ReportMediaState} from "../../app/portal/reports/media-actions";
import {portalText,type PortalLanguage} from "../../data/portal-i18n";
import {REPORT_MEDIA_MAX_FILES,UPLOAD_MAX_FILE_BYTES,UPLOAD_MAX_FILE_MB} from "../../lib/upload-config";

const initial:ReportMediaState={error:"",success:""};
export function ReportMediaUploadForm({reportId,language}:{reportId:number;language:PortalLanguage}){const[state,action]=useActionState(uploadReportMediaAction,initial),[clientError,setClientError]=useState(""),t=(value:string)=>portalText(language,value);function guard(event:FormEvent<HTMLFormElement>){const files=new FormData(event.currentTarget).getAll("files").filter((file):file is File=>file instanceof File);if(files.length>REPORT_MEDIA_MAX_FILES||files.some((file)=>file.size>UPLOAD_MAX_FILE_BYTES)){event.preventDefault();setClientError(files.length>REPORT_MEDIA_MAX_FILES?t("Too many photos selected."):t(`Each photo must be ${UPLOAD_MAX_FILE_MB} MB or smaller.`));}else setClientError("");}return <form action={action} onSubmit={guard} className="os-report-media-form"><input type="hidden" name="reportId" value={reportId}/><label>{t("Photos / Attachments")}<input name="files" type="file" accept="image/jpeg,image/png,image/webp" multiple required/><small>{t("Select up to 4 JPG, PNG or WebP images. Maximum 25 MB each.")}</small></label><label>{t("Caption (optional)")}<input name="caption" maxLength={240}/></label><label>{t("Area / location")}<input name="area" maxLength={160}/></label><label>{t("Notes")}<textarea name="notes" maxLength={2000} rows={3}/></label><Submit label={t("Attach photos")}/>{clientError&&<p className="os-form-error" role="alert">{clientError}</p>}{state.error&&<p className="os-form-error" role="alert">{t(state.error)}</p>}{state.success&&<p className="os-form-success" role="status">{t(state.success)}</p>}</form>}
function Submit({label}:{label:string}){const{pending}=useFormStatus();return <button className="os-primary-action" type="submit" disabled={pending}>{pending?"…":label}</button>}
