"use client";
import { useActionState,useState,type FormEvent } from "react";
import { useFormStatus } from "react-dom";
import { uploadDocumentFormAction,uploadPhotoFormAction } from "../../app/portal/projects/media-actions";
import { UPLOAD_MAX_FILE_BYTES,UPLOAD_MAX_FILE_MB } from "../../lib/upload-config";
const categories=["Drawings","Method statements","DVP / DOP","HSE / Risk assessments","Quality","Delivery documents","Certificates","Contracts / Commercial","Other"];
const initial={error:"",success:""};
function Submit({children}:{children:string}){const {pending}=useFormStatus();return <button className="os-primary-action" type="submit" disabled={pending}>{pending?"Uploading…":children}</button>}
function Result({state}:{state:typeof initial}){return <>{state.error&&<p className="os-form-error" role="alert">{state.error}</p>}{state.success&&<p className="os-form-success" role="status">{state.success}</p>}</>}
function useUploadGuard(){const [error,setError]=useState("");const guard=(event:FormEvent<HTMLFormElement>)=>{const file=new FormData(event.currentTarget).get("file");if(file instanceof File&&file.size>UPLOAD_MAX_FILE_BYTES){event.preventDefault();setError(`File exceeds the ${UPLOAD_MAX_FILE_MB} MB limit.`);}else setError("");};return {error,guard};}
export function DocumentUploadForm({projectId,today}:{projectId:string;today:string}){const [state,action]=useActionState(uploadDocumentFormAction,initial);const guard=useUploadGuard();return <form action={action} onSubmit={guard.guard} className="os-mini-form"><input type="hidden" name="projectId" value={projectId}/><label>File<input name="file" type="file" accept=".pdf,.docx,.xlsx,.csv,.txt,.jpg,.jpeg,.png" required/></label><label>Title<input name="title" maxLength={200} required/></label><label>Category<select name="category">{categories.map((category)=><option key={category}>{category}</option>)}</select></label><label>Revision<input name="revision" maxLength={40} placeholder="Rev.0" required/></label><label>Document date<input name="documentDate" type="date" defaultValue={today} required/></label><label>Status<select name="status"><option>Current</option><option>Review</option><option>Archived</option></select></label><label className="wide">Description / notes<textarea name="description" maxLength={2000}/></label><div className="wide"><Submit>Upload document</Submit>{guard.error?<p className="os-form-error" role="alert">{guard.error}</p>:<Result state={state}/>}</div></form>}
export function PhotoUploadForm({projectId,today}:{projectId:string;today:string}){const [state,action]=useActionState(uploadPhotoFormAction,initial);const guard=useUploadGuard();return <form action={action} onSubmit={guard.guard} className="os-mini-form"><input type="hidden" name="projectId" value={projectId}/><label>Photo<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Photo date<input name="photoDate" type="date" defaultValue={today} required/></label><label>Caption<input name="caption" maxLength={240} required/></label><label>Area / location<input name="area" maxLength={160}/></label><label className="wide">Notes<textarea name="notes" maxLength={2000}/></label><div className="wide"><Submit>Upload photo</Submit>{guard.error?<p className="os-form-error" role="alert">{guard.error}</p>:<Result state={state}/>}</div></form>}
