import ExcelJS from "exceljs";
import {createHash} from "node:crypto";
import {elementTypes,type ElementImportCandidate,type ElementType} from "./elements.ts";

export const syncFields=["code","elementType","floor","zone","drawingRef","description","weight","length","width","height","supplier","plannedDeliveryDate"] as const;
export type SyncField=(typeof syncFields)[number];
export type ColumnMapping=Partial<Record<SyncField,string>>;
export type WorkbookColumn={key:string;label:string;column:number;samples:string[]};
export type WorkbookRawRow={rowNumber:number;cells:string[]};
export type WorkbookSheet={name:string;headerRow:number;columns:WorkbookColumn[];rows:WorkbookRawRow[];headerCandidates:number[]};
export type SyncElement=Omit<ElementImportCandidate,"row">&{row?:number;id?:number;status?:string;installedReportId?:number|null;installationDate?:string;sourceKey?:string};
export type SyncDiff={newRows:SyncElement[];changed:Array<{existing:SyncElement;incoming:SyncElement;changes:Array<{field:SyncField;oldValue:string|number|null;newValue:string|number|null}>}>;unchanged:SyncElement[];missing:SyncElement[];conflicts:Array<{incoming:SyncElement;potential:SyncElement[]}>;installedAffected:number};
export type ValidationCode="required_mapping"|"missing_code"|"duplicate_code"|"invalid_type"|"invalid_number"|"invalid_date";
export type ValidationIssue={row:number|null;field:SyncField|null;code:ValidationCode;message:string;value?:string};
export type UnknownTypeGroup={normalizedValue:string;sourceValue:string;occurrences:number;rows:number[];sampleCodes:string[]};
export type DuplicateRowDiagnostic={row:number;code:string;sourceType:string;floor:string;zone:string;drawingRef:string;dimensions:string;weight:string};
export type DuplicateCodeGroup={code:string;rows:DuplicateRowDiagnostic[]};

const aliases:Record<SyncField,string[]>={
  code:["element","element code","code","mark","element mark","marka","element no","element number","position","poz","pozicija","marķējums","izdelie","марка","код","номер элемента"],
  elementType:["type","element type","category","product type","tip","tip elementa","veids","elementa tips","тип","тип элемента"],
  floor:["floor","level","storey","stavs","stāvs","этаж"],
  zone:["zone","section","zona","секция","зона"],
  drawingRef:["drawing reference","drawing","reference","drawing ref","drawing no","rasējums","чертеж","чертёж"],
  description:["description","name","apraksts","описание"],
  weight:["weight","mass","svars","вес","масса"],
  length:["length","garums","длина"],
  width:["width","platums","ширина"],
  height:["height","augstums","высота"],
  supplier:["supplier","manufacturer","piegādātājs","поставщик","производитель"],
  plannedDeliveryDate:["planned delivery date","delivery date","planned delivery","plan delivery","plānotais piegādes datums","плановая дата поставки"]
};

const typeAliases:Record<string,ElementType>={
  "wall":"Wall panel","wall panel":"Wall panel","siena":"Wall panel","sienas panelis":"Wall panel","стена":"Wall panel","стеновая панель":"Wall panel",
  "hollow core":"Hollow core slab","hollow core slab":"Hollow core slab","hc":"Hollow core slab","dobais parsegums":"Hollow core slab","dobais pārsegums":"Hollow core slab","пустотная плита":"Hollow core slab",
  "solid slab":"Solid slab","slab":"Solid slab","pilna platne":"Solid slab","pilnā plātne":"Solid slab","сплошная плита":"Solid slab",
  "beam":"Beam","sija":"Beam","балка":"Beam","column":"Column","kolonna":"Column","колонна":"Column",
  "stair":"Stair","stairs":"Stair","kapnes":"Stair","kāpnes":"Stair","лестница":"Stair",
  "balcony":"Balcony","balkons":"Balcony","балкон":"Balcony","parapet":"Parapet","parapets":"Parapet","парапет":"Parapet",
  "landing":"Landing","kapnu laukums":"Landing","kāpņu laukums":"Landing","лестничная площадка":"Landing",
  "steel":"Steel element","steel element":"Steel element","terauda elements":"Steel element","tērauda elements":"Steel element","стальной элемент":"Steel element",
  "other":"Other","cits":"Other","другое":"Other"
};
const additionalTypeAliases:Record<string,ElementType>={"sandwich wall":"Wall panel","sandwich panel":"Wall panel","solid wall":"Wall panel","hcs":"Hollow core slab","doba parseguma panelis":"Hollow core slab","dobā pārseguma panelis":"Hollow core slab","stair flight":"Stair","staircase":"Stair","balcony slab":"Balcony","parapeta panelis":"Parapet","landing slab":"Landing"};

export function normalizeHeader(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").trim().toLocaleLowerCase().replace(/[№#]/g," no ").replace(/[^\p{L}\p{N}]+/gu," ").replace(/\s+/g," ").trim();}
const normalizedAliases=Object.fromEntries(syncFields.map((field)=>[field,new Set(aliases[field].map(normalizeHeader))])) as Record<SyncField,Set<string>>;
export function autoMapHeaders(columns:Array<WorkbookColumn>|string[]):ColumnMapping{const entries=columns.map((column,index)=>typeof column==="string"?{key:column,label:column,column:index+1,samples:[]}:column),result:ColumnMapping={};for(const field of syncFields){const match=entries.find((column)=>normalizedAliases[field].has(normalizeHeader(column.label)));if(match)result[field]=match.key;}return result;}
function cellText(value:ExcelJS.CellValue):string{if(value===null||value===undefined)return"";if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="object"){if("result" in value)return cellText(value.result as ExcelJS.CellValue);if("text" in value)return String(value.text).trim();return"";}return String(value).trim();}
function rowScore(cells:string[]){const normalizedCells=cells.filter(Boolean).map(normalizeHeader),matches=syncFields.reduce((count,field)=>count+(normalizedCells.some((cell)=>normalizedAliases[field].has(cell))?1:0),0);return matches*10+Math.min(normalizedCells.length,8);}
export function detectHeaderRow(rows:WorkbookRawRow[]){const ranked=rows.filter((row)=>row.rowNumber<=50).map((row)=>({row:row.rowNumber,score:rowScore(row.cells)})).filter((row)=>row.score>=12).sort((a,b)=>b.score-a.score||a.row-b.row);return{headerRow:ranked[0]?.row??rows.find((row)=>row.cells.filter(Boolean).length>=2)?.rowNumber??1,candidates:ranked.slice(0,8).map((row)=>row.row)};}
export function prepareWorksheet(sheet:WorkbookSheet,headerRow=sheet.headerRow):WorkbookSheet{const header=sheet.rows.find((row)=>row.rowNumber===headerRow),counts=new Map<string,number>(),columns:WorkbookColumn[]=[];(header?.cells??[]).forEach((label,index)=>{if(!label)return;const base=label.trim(),seen=(counts.get(base)??0)+1;counts.set(base,seen);const key=`c${index+1}`,samples=sheet.rows.filter((row)=>row.rowNumber>headerRow).map((row)=>row.cells[index]??"").filter(Boolean).slice(0,3);columns.push({key,label:seen===1?base:`${base} (${seen})`,column:index+1,samples});});return{...sheet,headerRow,columns};}
export async function inspectXlsx(bytes:Buffer):Promise<{hash:string;sheets:WorkbookSheet[]}>{const workbook=new ExcelJS.Workbook();workbook.calcProperties.fullCalcOnLoad=false;await workbook.xlsx.load(bytes as unknown as ExcelJS.Buffer);const sheets:WorkbookSheet[]=[];workbook.eachSheet((sheet)=>{const rows:WorkbookRawRow[]=[];for(let rowNumber=1;rowNumber<=Math.min(sheet.rowCount,10002);rowNumber++){const row=sheet.getRow(rowNumber),cells:Array<string>=[];for(let column=1;column<=Math.min(sheet.columnCount,200);column++)cells.push(cellText(row.getCell(column).value));if(cells.some(Boolean))rows.push({rowNumber,cells});}if(!rows.length)return;const detected=detectHeaderRow(rows),base:WorkbookSheet={name:sheet.name,headerRow:detected.headerRow,columns:[],rows,headerCandidates:detected.candidates};sheets.push(prepareWorksheet(base));});if(!sheets.length)throw new Error("Workbook contains no usable worksheets.");return{hash:createHash("sha256").update(bytes).digest("hex"),sheets};}
export function normalizeElementType(value:string):ElementType|null{const exact=elementTypes.find((type)=>normalizeHeader(type)===normalizeHeader(value));return exact??typeAliases[normalizeHeader(value)]??additionalTypeAliases[normalizeHeader(value)]??null;}
export function validateRequiredMapping(mapping:ColumnMapping):ValidationIssue[]{return(["code","elementType"] as SyncField[]).filter((field)=>!mapping[field]).map((field)=>({row:null,field,code:"required_mapping",message:"Required field is not mapped. Select the XLSX column manually."}));}
export function mapWorkbookRows(sheet:WorkbookSheet,mapping:ColumnMapping){const errors:ValidationIssue[]=validateRequiredMapping(mapping),candidates:ElementImportCandidate[]=[];if(errors.length)return{candidates,errors};const mappedColumns=Object.values(mapping).filter(Boolean) as string[],columnIndex=new Map(sheet.columns.map((column)=>[column.key,column.column-1]));for(const row of sheet.rows.filter((item)=>item.rowNumber>sheet.headerRow)){const get=(field:SyncField)=>{const key=mapping[field],index=key?columnIndex.get(key):undefined;return index===undefined?"":String(row.cells[index]??"").trim();},mappedValues=mappedColumns.map((key)=>row.cells[columnIndex.get(key)??-1]??"").filter(Boolean),code=get("code"),rawType=get("elementType");if(!mappedValues.length)continue;if(!rawType&&mappedValues.length<2)continue;if(!code&&!rawType&&mappedValues.length<2)continue;if(!code){errors.push({row:row.rowNumber,field:"code",code:"missing_code",message:"Element code is missing."});continue;}const elementType=normalizeElementType(rawType);if(!elementType){errors.push({row:row.rowNumber,field:"elementType",code:"invalid_type",message:"Unknown element type.",value:rawType});continue;}const numeric=(field:SyncField)=>{const value=get(field);if(!value)return null;const parsed=Number(value.replace(/\s/g,"").replace(",","."));return Number.isFinite(parsed)&&parsed>=0?parsed:NaN;},weight=numeric("weight"),length=numeric("length"),width=numeric("width"),height=numeric("height"),plannedDeliveryDate=get("plannedDeliveryDate");if([weight,length,width,height].some(Number.isNaN)){errors.push({row:row.rowNumber,field:null,code:"invalid_number",message:"Dimensions and weight must be non-negative numbers."});continue;}if(plannedDeliveryDate&&!/^\d{4}-\d{2}-\d{2}$/.test(plannedDeliveryDate)){errors.push({row:row.rowNumber,field:"plannedDeliveryDate",code:"invalid_date",message:"Planned delivery date must use YYYY-MM-DD.",value:plannedDeliveryDate});continue;}candidates.push({row:row.rowNumber,code,elementType,floor:get("floor"),zone:get("zone"),drawingRef:get("drawingRef"),description:get("description"),weight,length,width,height,supplier:get("supplier"),plannedDeliveryDate});}return{candidates,errors};}
export function analyzeWorkbookIssues(sheet:WorkbookSheet,mapping:ColumnMapping,typeMappings:Record<string,ElementType>={},excludedRows:number[]=[]){const columnIndex=new Map(sheet.columns.map((column)=>[column.key,column.column-1])),excluded=new Set(excludedRows),unknown=new Map<string,UnknownTypeGroup>(),codes=new Map<string,DuplicateRowDiagnostic[]>(),get=(row:WorkbookRawRow,field:SyncField)=>{const key=mapping[field],index=key?columnIndex.get(key):undefined;return index===undefined?"":String(row.cells[index]??"").trim();};for(const row of sheet.rows.filter((item)=>item.rowNumber>sheet.headerRow&&!excluded.has(item.rowNumber))){const code=get(row,"code"),sourceType=get(row,"elementType"),meaningful=[code,sourceType,get(row,"floor"),get(row,"zone"),get(row,"drawingRef"),get(row,"weight"),get(row,"length"),get(row,"width"),get(row,"height")].filter(Boolean);if(!meaningful.length||(!sourceType&&meaningful.length<2))continue;const normalizedValue=normalizeHeader(sourceType),canonical=normalizeElementType(sourceType)??typeMappings[normalizedValue]??null;if(sourceType&&!canonical){const current=unknown.get(normalizedValue)??{normalizedValue,sourceValue:sourceType,occurrences:0,rows:[],sampleCodes:[]};current.occurrences++;current.rows.push(row.rowNumber);if(code&&current.sampleCodes.length<5&&!current.sampleCodes.includes(code))current.sampleCodes.push(code);unknown.set(normalizedValue,current);}if(code){const diagnostic:DuplicateRowDiagnostic={row:row.rowNumber,code,sourceType,floor:get(row,"floor"),zone:get(row,"zone"),drawingRef:get(row,"drawingRef"),dimensions:[get(row,"length"),get(row,"width"),get(row,"height")].filter(Boolean).join(" × "),weight:get(row,"weight")},key=code.toLocaleLowerCase(),list=codes.get(key)??[];list.push(diagnostic);codes.set(key,list);}}return{unknownTypes:[...unknown.values()],duplicates:[...codes.values()].filter((rows)=>rows.length>1).map((rows)=>({code:rows[0].code,rows}))};}
export function mapWorkbookRowsWithOverrides(sheet:WorkbookSheet,mapping:ColumnMapping,typeMappings:Record<string,ElementType>,excludedRows:number[]){const typeKey=mapping.elementType,typeColumn=typeKey?sheet.columns.find((column)=>column.key===typeKey)?.column:undefined,excluded=new Set(excludedRows),rows=sheet.rows.filter((row)=>!excluded.has(row.rowNumber)).map((row)=>{if(!typeColumn)return row;const cells=[...row.cells],raw=String(cells[typeColumn-1]??"").trim(),mapped=typeMappings[normalizeHeader(raw)];if(mapped)cells[typeColumn-1]=mapped;return{...row,cells};});return mapWorkbookRows({...sheet,rows},mapping);}
export function summarizeValidation(errors:ValidationIssue[]){const counts=new Map<ValidationCode,number>();for(const error of errors)counts.set(error.code,(counts.get(error.code)??0)+1);return[...counts].map(([code,count])=>({code,count}));}
const designFields=syncFields.filter((field)=>field!=="code");
const signature=(row:SyncElement)=>JSON.stringify(designFields.map((field)=>row[field]??null));
export function compareElementRegister(existing:SyncElement[],incoming:SyncElement[]):SyncDiff{
  const newRows:SyncElement[]=[],changed:SyncDiff["changed"]=[],unchanged:SyncElement[]=[],missing:SyncElement[]=[],conflicts:SyncDiff["conflicts"]=[],matchedIds=new Set<number>();
  const codes=new Set([...existing,...incoming].map((row)=>row.code.toLocaleLowerCase()));
  for(const code of codes){const oldGroup=existing.filter((row)=>row.code.toLocaleLowerCase()===code).sort((a,b)=>(a.id??0)-(b.id??0)),newGroup=incoming.filter((row)=>row.code.toLocaleLowerCase()===code).sort((a,b)=>(a.row??0)-(b.row??0));if(!oldGroup.length){newRows.push(...newGroup);continue;}if(!newGroup.length){missing.push(...oldGroup);continue;}
    const remainingOld=[...oldGroup],remainingNew=[...newGroup];
    for(let i=remainingNew.length-1;i>=0;i--){const candidate=remainingNew[i],matches=remainingOld.filter((row)=>signature(row)===signature(candidate));if(!matches.length)continue;const current=matches[0],oldIndex=remainingOld.indexOf(current);remainingOld.splice(oldIndex,1);remainingNew.splice(i,1);candidate.matchedElementId=current.id;if(current.id)matchedIds.add(current.id);unchanged.push(current);}
    if(remainingOld.length===1&&remainingNew.length===1){const current=remainingOld[0],candidate=remainingNew[0];candidate.matchedElementId=current.id;if(current.id)matchedIds.add(current.id);const changes=designFields.filter((field)=>current[field]!==candidate[field]).map((field)=>({field,oldValue:current[field] as string|number|null,newValue:candidate[field] as string|number|null}));if(changes.length)changed.push({existing:current,incoming:candidate,changes});else unchanged.push(current);remainingOld.length=0;remainingNew.length=0;}
    if(remainingOld.length&&remainingNew.length){for(const candidate of remainingNew)conflicts.push({incoming:candidate,potential:[...remainingOld]});}else newRows.push(...remainingNew);
    missing.push(...remainingOld.filter((row)=>!conflicts.some((conflict)=>conflict.potential.includes(row))));
  }
  return{newRows,changed,unchanged,missing,conflicts,installedAffected:existing.filter((row)=>row.status==="Installed"&&matchedIds.has(row.id??-1)).length};
}
