export const elementTypes=["Wall panel","Hollow core slab","Solid slab","Beam","Column","Stair","Balcony","Parapet","Landing","Steel element","Other"] as const;
export const elementStatuses=["Planned","Expected","Delivered","On site","Installed","Issue","Rejected / Hold","Replaced"] as const;
export type ElementType=(typeof elementTypes)[number];
export type ElementStatus=(typeof elementStatuses)[number];
export type ElementSummaryInput={id:number;code:string;elementType:string;floor:string;zone:string;status:string};
export function isInstallableStatus(status:string){return ["Planned","Expected","Delivered","On site"].includes(status);}
export function validateInstallationSelection(rows:ElementSummaryInput[],ids:number[]){const unique=[...new Set(ids)],byId=new Map(rows.map((row)=>[row.id,row]));if(unique.length!==ids.length)return{valid:false,error:"Duplicate element selection."};for(const id of unique){const row=byId.get(id);if(!row||!isInstallableStatus(row.status))return{valid:false,error:"Selected element is no longer available for installation."};}return{valid:true,error:""};}
export function validateBulkOperationalStatus(rows:ElementSummaryInput[],ids:number[],nextStatus:string){if(!["Expected","Delivered","On site"].includes(nextStatus))return{valid:false,error:"Invalid bulk status."};const unique=[...new Set(ids)],byId=new Map(rows.map((row)=>[row.id,row]));if(!unique.length||unique.length!==ids.length)return{valid:false,error:"Invalid element selection."};for(const id of unique){const row=byId.get(id);if(!row||row.status==="Installed"||["Issue","Rejected / Hold","Replaced"].includes(row.status))return{valid:false,error:"Selected element requires individual review."};}return{valid:true,error:""};}
export function elementRoleCapabilities(role:string){return{view:role!=="Employee",operate:["Foreman","Project Manager","Administrator","Director"].includes(role),manage:["Project Manager","Administrator","Director"].includes(role),correct:["Project Manager","Administrator","Director"].includes(role)};}
export function filterElements<T extends ElementSummaryInput>(rows:T[],filters:{q?:string;floor?:string;zone?:string;type?:string;status?:string}){const q=(filters.q??"").trim().toLocaleLowerCase();return rows.filter((row)=>(!q||`${row.code} ${row.elementType}`.toLocaleLowerCase().includes(q))&&(!filters.floor||row.floor===filters.floor)&&(!filters.zone||row.zone===filters.zone)&&(!filters.type||row.elementType===filters.type)&&(!filters.status||row.status===filters.status));}
export function elementProgress(rows:ElementSummaryInput[]){const active=rows.filter((row)=>row.status!=="Replaced"),installed=active.filter((row)=>row.status==="Installed").length,total=active.length;return{total,installed,remaining:total-installed,percentage:total?Math.round(installed/total*100):0,byType:groupProgress(active,"elementType"),byFloor:groupProgress(active,"floor")};}
function groupProgress(rows:ElementSummaryInput[],key:"elementType"|"floor"){return [...new Set(rows.map((row)=>row[key]||"—"))].sort().map((value)=>{const group=rows.filter((row)=>(row[key]||"—")===value),installed=group.filter((row)=>row.status==="Installed").length;return{value,total:group.length,installed};});}
export const importHeaders=["Element code","Element type","Floor","Zone","Drawing/reference","Description","Weight","Length","Width","Height","Supplier","Planned delivery date"] as const;
export type ElementImportCandidate={row:number;code:string;elementType:string;floor:string;zone:string;drawingRef:string;description:string;weight:number|null;length:number|null;width:number|null;height:number|null;supplier:string;plannedDeliveryDate:string;sourceKey?:string;matchedElementId?:number};
// Kept for backward-compatible callers; existing marks are no longer uniqueness blockers.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function parseElementCsv(csv:string,_existingCodes:string[]=[]){const lines=csv.replace(/^\uFEFF/,"").split(/\r?\n/).filter((line)=>line.trim()),errors:string[]=[],candidates:ElementImportCandidate[]=[];if(!lines.length)return{candidates,errors:["Import file is empty."]};const headers=parseCsvLine(lines[0]);if(headers[0]!=="Element code")return{candidates,errors:["The first column must be Element code."]};for(let i=1;i<lines.length;i++){const cells=parseCsvLine(lines[i]),code=(cells[0]??"").trim(),elementType=(cells[1]??"").trim();if(!code){errors.push(`Row ${i+1}: Element code is required.`);continue;}if(!elementTypes.includes(elementType as ElementType)){errors.push(`Row ${i+1}: Invalid element type.`);continue;}const number=(index:number)=>{const value=(cells[index]??"").trim();if(!value)return null;const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=0?parsed:NaN;},weight=number(6),length=number(7),width=number(8),height=number(9);if([weight,length,width,height].some((value)=>Number.isNaN(value))){errors.push(`Row ${i+1}: Dimensions and weight must be non-negative numbers.`);continue;}const date=(cells[11]??"").trim();if(date&&!/^\d{4}-\d{2}-\d{2}$/.test(date)){errors.push(`Row ${i+1}: Planned delivery date must use YYYY-MM-DD.`);continue;}candidates.push({row:i+1,code,elementType,floor:(cells[2]??"").trim(),zone:(cells[3]??"").trim(),drawingRef:(cells[4]??"").trim(),description:(cells[5]??"").trim(),weight,length,width,height,supplier:(cells[10]??"").trim(),plannedDeliveryDate:date});}return{candidates,errors};}
function parseCsvLine(line:string){const result:string[]=[],pattern=/(?:^|,)(?:"((?:[^"]|"")*)"|([^",]*))/g;let match:RegExpExecArray|null;while((match=pattern.exec(line)))result.push((match[1]??match[2]??"").replace(/""/g,'"'));return result;}
