import { db } from "./db.ts";
import {deleteDraftReportRecords} from "./report-lifecycle.ts";
import {sanitizeCapabilityMap,type CapabilityMap} from "./project-access.ts";
import {defaultOrientation} from "./loads.ts";
import {compareElementsByMark} from "./elements.ts";

export type Project = { id: string; name: string; location: string; client: string; status: string; progress: number; peopleToday: number; nextDelivery: string; manager: string; managerEmployeeId: string | null; startDate: string; targetDate: string; description: string; latitude:number|null; longitude:number|null; archivedAt:string; archivedById:number|null };
export type Employee = { id: string; name: string; firstName: string; lastName: string; role: string; project: string; defaultProjectId: string | null; phone: string; email: string; status: string; employmentStartDate: string; employmentEndDate: string; notes: string; certificates: string[] };
export type DocumentRow = { id: string; name: string; category: string; project: string; revision: string; updated: string; status: string };
export type DailyReport = { id: number; projectId: string; project: string; date: string; people: number; work: string; deliveries: number; issues: number; weather: string; notes: string; author: string; reporterUserId: number|null; reporterEmployeeId: string|null; status: string; materials: string; equipment: string; problems: string; safety: string; additionalNotes: string; createdAt: string; updatedAt: string; submittedAt: string; approvedById: number|null; approvedAt: string };
export type AttendanceEntry = { id:number; reportId:number; employeeId:string; employeeName:string; position:string; projectId:string; projectName:string; date:string; status:string; regularHours:number; overtimeHours:number; comment:string };
export type TimesheetPeriod = { period:string; status:string; reviewedById:number|null; reviewedAt:string; closedById:number|null; closedAt:string };
export type ProjectEvent = { id: number; projectId: string; date: string; time: string; type: string; title: string; details: string; author: string };
export type ActivityLog = { id: number; actor: string; action: string; entityType: string; entityId: string; details: string; createdAt: string };
export type UserAccess = { id: number; name: string; email: string; role: string; active: number; createdAt: string };
export type Delivery = { id: number; projectId: string; deliveryDate: string; deliveryTime: string; supplier: string; loadRef: string; description: string; status: string; notes: string };
export type ProjectIssue = { id: number; projectId: string; createdDate: string; category: string; title: string; priority: string; status: string; owner: string; ownerEmployeeId: string | null; details: string };
export type ProjectPhoto = { id: number; projectId: string; reportId: number|null; photoDate: string; area: string; caption: string; fileRef: string; author: string; notes: string; originalFilename: string; storedPath: string; fileSize: number; mimeType: string; uploadedById: number|null; uploadedAt: string };
export type ProjectDocument = { id:number; projectId:string; project:string; title:string; category:string; revision:string; documentDate:string; status:string; description:string; originalFilename:string; storedPath:string; fileSize:number; mimeType:string; uploadedById:number|null; uploadedBy:string; uploadedAt:string };
export type ProjectMember = Employee & { projectRole: string; assignedAt: string };
export type ProjectElement={id:number;projectId:string;projectName:string;code:string;elementType:string;floor:string;zone:string;drawingRef:string;description:string;weight:number|null;length:number|null;width:number|null;height:number|null;supplier:string;plannedDeliveryDate:string;actualDeliveryDate:string;installationDate:string;status:string;issueNote:string;notes:string;active:number;installedReportId:number|null;createdAt:string;updatedAt:string;createdImportId:number|null;lastImportId:number|null;lastSourceRevision:string;sourcePresence:string;sourceKey:string;sourceRow:number|null;installationZoneId:number|null;installationZoneName:string};
export type ElementHistory={id:number;elementId:number;fromStatus:string;toStatus:string;eventDate:string;reportId:number|null;actorUserId:number|null;actor:string;note:string;createdAt:string};
export type ReportWeather={id:number;reportId:number;timepoint:string;temperature:number|null;conditionCode:number|null;condition:string;precipitation:number|null;windSpeed:number|null;windGust:number|null;provider:string;retrievedAt:string};
export type ElementImport={id:number;projectId:string;originalFilename:string;sourceRevision:string;sourceHash:string;worksheetName:string;mappingJson:string;payloadJson:string;sourcePayloadJson:string;summaryJson:string;status:string;notes:string;importedById:number|null;importedBy:string;importedAt:string;appliedAt:string;appliedById:number|null;appliedBy:string};

const projectSelect = `SELECT id, name, location, client, status, progress, people_today AS peopleToday, next_delivery AS nextDelivery, manager, manager_employee_id AS managerEmployeeId, start_date AS startDate, target_date AS targetDate, description,latitude,longitude, archived_at AS archivedAt, archived_by_id AS archivedById FROM projects`;

export function listProjects(): Project[] { return db.prepare(`${projectSelect} ORDER BY CASE status WHEN 'Active' THEN 0 WHEN 'Planning' THEN 1 ELSE 2 END, name`).all() as unknown as Project[]; }
export function getProject(id: string): Project | undefined { return db.prepare(`${projectSelect} WHERE id = ?`).get(id) as Project | undefined; }
export function getProjectByName(name: string): Project | undefined { return db.prepare(`${projectSelect} WHERE name = ? COLLATE NOCASE`).get(name) as Project | undefined; }
export function createProject(input: Pick<Project, "id" | "name" | "location" | "client" | "status" | "manager" | "managerEmployeeId" | "startDate" | "targetDate" | "description"|"latitude"|"longitude">) {
  return db.prepare(`INSERT INTO projects (id,name,location,client,status,manager,manager_employee_id,start_date,target_date,description,latitude,longitude) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.id,input.name,input.location,input.client,input.status,input.manager,input.managerEmployeeId,input.startDate,input.targetDate,input.description,input.latitude,input.longitude);
}
export function updateProject(id: string, previousName: string, input: Pick<Project, "name" | "location" | "client" | "status" | "manager" | "managerEmployeeId" | "startDate" | "targetDate" | "description"|"latitude"|"longitude">) {
  const result=db.prepare(`UPDATE projects SET name=?,location=?,client=?,status=?,manager=?,manager_employee_id=?,start_date=?,target_date=?,description=?,latitude=?,longitude=? WHERE id=?`).run(input.name,input.location,input.client,input.status,input.manager,input.managerEmployeeId,input.startDate,input.targetDate,input.description,input.latitude,input.longitude,id);
  if (previousName !== input.name) {
    db.prepare("UPDATE reports SET project_name=? WHERE project_id=?").run(input.name,id);
    db.prepare("UPDATE documents SET project=? WHERE project=?").run(input.name,previousName);
    db.prepare("UPDATE employees SET project=? WHERE project=?").run(input.name,previousName);
  }
  return result;
}
export function listEmployees(): Employee[] {
  const rows=db.prepare(`SELECT e.id,e.name,e.first_name AS firstName,e.last_name AS lastName,e.role,COALESCE((SELECT GROUP_CONCAT(p.name, ', ') FROM project_members m JOIN projects p ON p.id=m.project_id WHERE m.employee_id=e.id),'—') AS project,e.default_project_id AS defaultProjectId,e.phone,e.email,e.employment_status AS status,e.employment_start_date AS employmentStartDate,e.employment_end_date AS employmentEndDate,e.notes,e.certificates FROM employees e ORDER BY e.name`).all() as unknown as (Omit<Employee,"certificates">&{certificates:string})[];
  return rows.map((row)=>({...row,certificates:JSON.parse(row.certificates) as string[]}));
}
export function getEmployee(id:string):Employee|undefined{return listEmployees().find((employee)=>employee.id===id);}
export function listDocuments(): DocumentRow[] { return db.prepare("SELECT id, name, category, project, revision, updated, status FROM documents ORDER BY updated DESC").all() as unknown as DocumentRow[]; }
export function listReports():DailyReport[]{return db.prepare(`SELECT id,project_id AS projectId,project_name AS project,report_date AS date,people,work,deliveries,issues,weather,notes,author,reporter_user_id AS reporterUserId,reporter_employee_id AS reporterEmployeeId,status,materials,equipment,problems,safety,additional_notes AS additionalNotes,created_at AS createdAt,updated_at AS updatedAt,submitted_at AS submittedAt,approved_by_id AS approvedById,approved_at AS approvedAt FROM reports ORDER BY report_date DESC,id DESC`).all() as unknown as DailyReport[];}
export function getReport(id:number):DailyReport|undefined{return listReports().find((report)=>report.id===id);}

export function listProjectEvents(projectId: string): ProjectEvent[] {
  return db.prepare(`SELECT id, project_id AS projectId, event_date AS date, event_time AS time, event_type AS type, title, details, author FROM project_events WHERE project_id = ? ORDER BY event_date DESC, event_time DESC, id DESC`).all(projectId) as unknown as ProjectEvent[];
}
export function addProjectEvent(input: Omit<ProjectEvent, "id">) {
  return db.prepare(`INSERT INTO project_events (project_id, event_date, event_time, event_type, title, details, author) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(input.projectId, input.date, input.time, input.type, input.title, input.details, input.author);
}
export function logActivity(input: { userId?: number; actor: string; action: string; entityType: string; entityId?: string; details?: string }) {
  return db.prepare(`INSERT INTO activity_log (user_id, actor, action, entity_type, entity_id, details) VALUES (?, ?, ?, ?, ?, ?)`).run(input.userId ?? null, input.actor, input.action, input.entityType, input.entityId ?? "", input.details ?? "");
}
export function listActivity(limit = 20): ActivityLog[] {
  return db.prepare(`SELECT id, actor, action, entity_type AS entityType, entity_id AS entityId, details, created_at AS createdAt FROM activity_log ORDER BY id DESC LIMIT ?`).all(limit) as unknown as ActivityLog[];
}
export function listProjectActivity(projectId: string): ActivityLog[] {
  return db.prepare(`SELECT id, actor, action, entity_type AS entityType, entity_id AS entityId, details, created_at AS createdAt FROM activity_log WHERE entity_type = 'project' AND entity_id = ? ORDER BY id DESC`).all(projectId) as unknown as ActivityLog[];
}
export function listUsers(): UserAccess[] {
  return db.prepare(`SELECT id, name, email, role, active, created_at AS createdAt FROM users ORDER BY CASE role WHEN 'Director' THEN 0 WHEN 'Administrator' THEN 1 WHEN 'Project Manager' THEN 2 WHEN 'Foreman' THEN 3 ELSE 4 END, name`).all() as unknown as UserAccess[];
}
export function getUserAccess(id: number): UserAccess | undefined {
  return db.prepare(`SELECT id, name, email, role, active, created_at AS createdAt FROM users WHERE id=?`).get(id) as UserAccess | undefined;
}
export function getUserAccessByEmail(email: string): UserAccess | undefined {
  return db.prepare(`SELECT id, name, email, role, active, created_at AS createdAt FROM users WHERE email=? COLLATE NOCASE`).get(email) as UserAccess | undefined;
}
export function createUserAccess(input: { name:string;email:string;role:string;active:number;passwordHash:string }) {
  return db.prepare(`INSERT INTO users(name,email,role,active,password_hash) VALUES(?,?,?,?,?)`).run(input.name,input.email,input.role,input.active,input.passwordHash);
}
export function updateUserAccess(id:number,input:{name:string;email:string;role:string;active:number}) {
  return db.prepare(`UPDATE users SET name=?,email=?,role=?,active=? WHERE id=?`).run(input.name,input.email,input.role,input.active,id);
}

export function listDeliveries(projectId: string): Delivery[] {
  return db.prepare(`SELECT id, project_id AS projectId, delivery_date AS deliveryDate, delivery_time AS deliveryTime, supplier, load_ref AS loadRef, description, status, notes FROM deliveries WHERE project_id = ? ORDER BY delivery_date DESC, delivery_time DESC, id DESC`).all(projectId) as unknown as Delivery[];
}
export function listProjectIssues(projectId: string): ProjectIssue[] {
  return db.prepare(`SELECT id, project_id AS projectId, created_date AS createdDate, category, title, priority, status, owner, owner_employee_id AS ownerEmployeeId, details FROM project_issues WHERE project_id = ? ORDER BY CASE status WHEN 'Open' THEN 0 WHEN 'In progress' THEN 1 ELSE 2 END, id DESC`).all(projectId) as unknown as ProjectIssue[];
}
export function listProjectPhotos(projectId: string): ProjectPhoto[] {
  return db.prepare(`SELECT id,project_id AS projectId,report_id AS reportId,photo_date AS photoDate,area,caption,file_ref AS fileRef,author,notes,original_filename AS originalFilename,stored_path AS storedPath,file_size AS fileSize,mime_type AS mimeType,uploaded_by_id AS uploadedById,uploaded_at AS uploadedAt FROM project_photos WHERE project_id=? ORDER BY photo_date DESC,id DESC`).all(projectId) as unknown as ProjectPhoto[];
}
export function listProjectDocuments(projectId?:string): ProjectDocument[] { const where=projectId?"WHERE d.project_id = ?":""; return db.prepare(`SELECT d.id,d.project_id AS projectId,p.name AS project,d.title,d.category,d.revision,d.document_date AS documentDate,d.status,d.description,d.original_filename AS originalFilename,d.stored_path AS storedPath,d.file_size AS fileSize,d.mime_type AS mimeType,d.uploaded_by_id AS uploadedById,d.uploaded_by AS uploadedBy,d.uploaded_at AS uploadedAt FROM project_documents d JOIN projects p ON p.id=d.project_id ${where} ORDER BY d.uploaded_at DESC,d.id DESC`).all(...(projectId?[projectId]:[])) as unknown as ProjectDocument[]; }
export function getProjectDocument(id:number):ProjectDocument|undefined{return db.prepare(`SELECT d.id,d.project_id AS projectId,p.name AS project,d.title,d.category,d.revision,d.document_date AS documentDate,d.status,d.description,d.original_filename AS originalFilename,d.stored_path AS storedPath,d.file_size AS fileSize,d.mime_type AS mimeType,d.uploaded_by_id AS uploadedById,d.uploaded_by AS uploadedBy,d.uploaded_at AS uploadedAt FROM project_documents d JOIN projects p ON p.id=d.project_id WHERE d.id=?`).get(id) as ProjectDocument|undefined;}
export function createProjectDocument(input:Omit<ProjectDocument,"id"|"project"|"uploadedAt">){return db.prepare(`INSERT INTO project_documents(project_id,title,category,revision,document_date,status,description,original_filename,stored_path,file_size,mime_type,uploaded_by_id,uploaded_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.projectId,input.title,input.category,input.revision,input.documentDate,input.status,input.description,input.originalFilename,input.storedPath,input.fileSize,input.mimeType,input.uploadedById,input.uploadedBy);}
export function updateProjectDocumentMetadata(id:number,input:Pick<ProjectDocument,"title"|"category"|"revision"|"documentDate"|"status"|"description">){return db.prepare(`UPDATE project_documents SET title=?,category=?,revision=?,document_date=?,status=?,description=? WHERE id=?`).run(input.title,input.category,input.revision,input.documentDate,input.status,input.description,id);}
export function deleteProjectDocument(id:number){return db.prepare("DELETE FROM project_documents WHERE id=?").run(id);}
export function getProjectPhoto(id:number):ProjectPhoto|undefined{return db.prepare(`SELECT id,project_id AS projectId,report_id AS reportId,photo_date AS photoDate,area,caption,file_ref AS fileRef,author,notes,original_filename AS originalFilename,stored_path AS storedPath,file_size AS fileSize,mime_type AS mimeType,uploaded_by_id AS uploadedById,uploaded_at AS uploadedAt FROM project_photos WHERE id=?`).get(id) as ProjectPhoto|undefined;}
export function listReportPhotos(reportId:number):ProjectPhoto[]{return db.prepare(`SELECT id,project_id AS projectId,report_id AS reportId,photo_date AS photoDate,area,caption,file_ref AS fileRef,author,notes,original_filename AS originalFilename,stored_path AS storedPath,file_size AS fileSize,mime_type AS mimeType,uploaded_by_id AS uploadedById,uploaded_at AS uploadedAt FROM project_photos WHERE report_id=? ORDER BY uploaded_at,id`).all(reportId) as unknown as ProjectPhoto[];}
export function createProjectPhoto(input:Omit<ProjectPhoto,"id"|"fileRef"|"uploadedAt"|"reportId">&{reportId?:number|null}){return db.prepare(`INSERT INTO project_photos(project_id,report_id,photo_date,area,caption,author,notes,original_filename,stored_path,file_size,mime_type,uploaded_by_id,uploaded_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(input.projectId,input.reportId??null,input.photoDate,input.area,input.caption,input.author,input.notes,input.originalFilename,input.storedPath,input.fileSize,input.mimeType,input.uploadedById);}
export function updateProjectPhotoMetadata(id:number,input:Pick<ProjectPhoto,"photoDate"|"area"|"caption"|"notes">){return db.prepare(`UPDATE project_photos SET photo_date=?,area=?,caption=?,notes=? WHERE id=?`).run(input.photoDate,input.area,input.caption,input.notes,id);}
export function deleteProjectPhoto(id:number){return db.prepare("DELETE FROM project_photos WHERE id=?").run(id);}
export function listProjectMembers(projectId: string): ProjectMember[] {
  const rows = db.prepare(`SELECT e.id,e.name,e.role,e.project,e.phone,e.status,e.certificates,m.project_role AS projectRole,m.assigned_at AS assignedAt FROM project_members m JOIN employees e ON e.id=m.employee_id WHERE m.project_id=? ORDER BY CASE m.project_role WHEN 'Project manager' THEN 0 WHEN 'Site lead' THEN 1 ELSE 2 END,e.name`).all(projectId) as unknown as (Omit<ProjectMember,"certificates"> & {certificates:string})[];
  return rows.map((row) => ({...row, certificates: JSON.parse(row.certificates) as string[]}));
}
export function assignProjectMember(projectId: string, employeeId: string, projectRole: string) { return db.prepare(`INSERT INTO project_members (project_id,employee_id,project_role) VALUES (?,?,?) ON CONFLICT(project_id,employee_id) DO UPDATE SET project_role=excluded.project_role`).run(projectId,employeeId,projectRole); }
export function removeProjectMember(projectId: string, employeeId: string) { return db.prepare(`DELETE FROM project_members WHERE project_id=? AND employee_id=?`).run(projectId,employeeId); }
export function unassignProjectIssues(projectId: string, employeeId: string) { return db.prepare(`UPDATE project_issues SET owner='',owner_employee_id=NULL WHERE project_id=? AND owner_employee_id=?`).run(projectId,employeeId); }
export function getDelivery(id: number): Delivery | undefined { return db.prepare(`SELECT id,project_id AS projectId,delivery_date AS deliveryDate,delivery_time AS deliveryTime,supplier,load_ref AS loadRef,description,status,notes FROM deliveries WHERE id=?`).get(id) as Delivery | undefined; }
export function saveDelivery(input: Omit<Delivery,"id"> & {id?:number}) { return input.id ? db.prepare(`UPDATE deliveries SET delivery_date=?,delivery_time=?,supplier=?,load_ref=?,description=?,status=?,notes=? WHERE id=? AND project_id=?`).run(input.deliveryDate,input.deliveryTime,input.supplier,input.loadRef,input.description,input.status,input.notes,input.id,input.projectId) : db.prepare(`INSERT INTO deliveries (project_id,delivery_date,delivery_time,supplier,load_ref,description,status,notes) VALUES (?,?,?,?,?,?,?,?)`).run(input.projectId,input.deliveryDate,input.deliveryTime,input.supplier,input.loadRef,input.description,input.status,input.notes); }
export function deleteDelivery(id: number, projectId: string) { return db.prepare(`DELETE FROM deliveries WHERE id=? AND project_id=?`).run(id,projectId); }
export function getProjectIssue(id: number): ProjectIssue | undefined { return db.prepare(`SELECT id,project_id AS projectId,created_date AS createdDate,category,title,priority,status,owner,owner_employee_id AS ownerEmployeeId,details FROM project_issues WHERE id=?`).get(id) as ProjectIssue | undefined; }
export function saveProjectIssue(input: Omit<ProjectIssue,"id"> & {id?:number}) { return input.id ? db.prepare(`UPDATE project_issues SET created_date=?,category=?,title=?,priority=?,status=?,owner=?,owner_employee_id=?,details=? WHERE id=? AND project_id=?`).run(input.createdDate,input.category,input.title,input.priority,input.status,input.owner,input.ownerEmployeeId,input.details,input.id,input.projectId) : db.prepare(`INSERT INTO project_issues (project_id,created_date,category,title,priority,status,owner,owner_employee_id,details) VALUES (?,?,?,?,?,?,?,?,?)`).run(input.projectId,input.createdDate,input.category,input.title,input.priority,input.status,input.owner,input.ownerEmployeeId,input.details); }
export function deleteProjectIssue(id: number, projectId: string) { return db.prepare(`DELETE FROM project_issues WHERE id=? AND project_id=?`).run(id,projectId); }

export type EmployeeInput={id:string;firstName:string;lastName:string;role:string;phone:string;email:string;status:string;defaultProjectId:string|null;employmentStartDate:string;employmentEndDate:string;notes:string};
export function createEmployee(input:EmployeeInput){return db.prepare(`INSERT INTO employees(id,name,first_name,last_name,role,project,phone,email,status,employment_status,default_project_id,employment_start_date,employment_end_date,notes,certificates) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.id,`${input.firstName} ${input.lastName}`.trim(),input.firstName,input.lastName,input.role,"",input.phone,input.email,"Office",input.status,input.defaultProjectId,input.employmentStartDate,input.employmentEndDate,input.notes,"[]");}
export function updateEmployee(id:string,input:Omit<EmployeeInput,"id">){return db.prepare(`UPDATE employees SET name=?,first_name=?,last_name=?,role=?,phone=?,email=?,employment_status=?,default_project_id=?,employment_start_date=?,employment_end_date=?,notes=? WHERE id=?`).run(`${input.firstName} ${input.lastName}`.trim(),input.firstName,input.lastName,input.role,input.phone,input.email,input.status,input.defaultProjectId,input.employmentStartDate,input.employmentEndDate,input.notes,id);}
export function setEmployeeStatus(id:string,status:string,endDate=""){return db.prepare(`UPDATE employees SET employment_status=?,employment_end_date=CASE WHEN ?<>'' THEN ? ELSE employment_end_date END WHERE id=?`).run(status,endDate,endDate,id);}
export function setEmployeeDefaultProject(employeeId:string,projectId:string|null,projectRole:string,startDate:string){
  db.prepare(`UPDATE employee_project_assignments SET end_date=? WHERE employee_id=? AND end_date='' AND project_id<>COALESCE(?,'')`).run(startDate,employeeId,projectId);
  if(projectId){db.prepare(`INSERT INTO employee_project_assignments(employee_id,project_id,project_role,start_date) SELECT ?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM employee_project_assignments WHERE employee_id=? AND project_id=? AND end_date='')`).run(employeeId,projectId,projectRole,startDate,employeeId,projectId);assignProjectMember(projectId,employeeId,projectRole);}
}
export function recordProjectAssignment(employeeId:string,projectId:string,projectRole:string,startDate:string){db.prepare(`INSERT INTO employee_project_assignments(employee_id,project_id,project_role,start_date) SELECT ?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM employee_project_assignments WHERE employee_id=? AND project_id=? AND end_date='')`).run(employeeId,projectId,projectRole,startDate,employeeId,projectId);}
export function closeProjectAssignment(employeeId:string,projectId:string,endDate:string){db.prepare(`UPDATE employee_project_assignments SET end_date=? WHERE employee_id=? AND project_id=? AND end_date=''`).run(endDate,employeeId,projectId);}
export function listEmployeeAssignments(employeeId:string){return db.prepare(`SELECT a.id,a.project_id AS projectId,p.name AS project,a.project_role AS projectRole,a.start_date AS startDate,a.end_date AS endDate FROM employee_project_assignments a JOIN projects p ON p.id=a.project_id WHERE a.employee_id=? ORDER BY a.start_date DESC,a.id DESC`).all(employeeId) as unknown as {id:number;projectId:string;project:string;projectRole:string;startDate:string;endDate:string}[];}
export function listProjectWorkforce(projectId:string):Employee[]{const rows=db.prepare(`SELECT e.id,e.name,e.first_name AS firstName,e.last_name AS lastName,e.role,p.name AS project,e.default_project_id AS defaultProjectId,e.phone,e.email,e.employment_status AS status,e.employment_start_date AS employmentStartDate,e.employment_end_date AS employmentEndDate,e.notes,e.certificates FROM project_members m JOIN employees e ON e.id=m.employee_id JOIN projects p ON p.id=m.project_id WHERE m.project_id=? AND e.employment_status<>'Inactive' ORDER BY e.name`).all(projectId) as unknown as (Omit<Employee,"certificates">&{certificates:string})[];return rows.map((row)=>({...row,certificates:JSON.parse(row.certificates) as string[]}));}
export function getUserEmployeeId(userId:number):string|null{return (db.prepare(`SELECT employee_id AS employeeId FROM users WHERE id=?`).get(userId) as {employeeId:string|null}|undefined)?.employeeId??null;}
export function listUserProjectIds(userId:number):string[]{const employeeId=getUserEmployeeId(userId);if(!employeeId)return[];return (db.prepare(`SELECT project_id AS projectId FROM project_members WHERE employee_id=? UNION SELECT id AS projectId FROM projects WHERE manager_employee_id=?`).all(employeeId,employeeId) as {projectId:string}[]).map((row)=>row.projectId);}

export type AttendanceInput={employeeId:string;status:string;regularHours:number;overtimeHours:number;comment:string};
export type ReportInput={id?:number;projectId:string;project:string;date:string;work:string;weather:string;materials:string;equipment:string;problems:string;safety:string;additionalNotes:string;author:string;reporterUserId:number;reporterEmployeeId:string|null;status:string;attendance:AttendanceInput[]};
export function saveDailyReport(input:ReportInput):number{
  let reportId=input.id??0;
  if(input.id){db.prepare(`UPDATE reports SET project_id=?,project_name=?,report_date=?,people=?,work=?,weather=?,notes=?,materials=?,equipment=?,problems=?,safety=?,additional_notes=?,status=?,updated_at=CURRENT_TIMESTAMP,submitted_at=CASE WHEN ?='Submitted' AND submitted_at='' THEN CURRENT_TIMESTAMP ELSE submitted_at END WHERE id=?`).run(input.projectId,input.project,input.date,input.attendance.filter((entry)=>entry.status==="Worked").length,input.work,input.weather,input.additionalNotes,input.materials,input.equipment,input.problems,input.safety,input.additionalNotes,input.status,input.status,input.id);}
  else{const result=db.prepare(`INSERT INTO reports(project_id,project_name,report_date,people,work,deliveries,issues,weather,notes,author,reporter_user_id,reporter_employee_id,status,materials,equipment,problems,safety,additional_notes,updated_at,submitted_at) VALUES(?,?,?,?,?,0,0,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CASE WHEN ?='Submitted' THEN CURRENT_TIMESTAMP ELSE '' END)`).run(input.projectId,input.project,input.date,input.attendance.filter((entry)=>entry.status==="Worked").length,input.work,input.weather,input.additionalNotes,input.author,input.reporterUserId,input.reporterEmployeeId,input.status,input.materials,input.equipment,input.problems,input.safety,input.additionalNotes,input.status);reportId=Number(result.lastInsertRowid);}
  const ids=input.attendance.map((entry)=>entry.employeeId);
  if(ids.length){const placeholders=ids.map(()=>"?").join(",");db.prepare(`DELETE FROM attendance_entries WHERE report_id=? AND employee_id NOT IN (${placeholders})`).run(reportId,...ids);}else db.prepare(`DELETE FROM attendance_entries WHERE report_id=?`).run(reportId);
  const upsert=db.prepare(`INSERT INTO attendance_entries(report_id,employee_id,project_id,work_date,attendance_status,regular_hours,overtime_hours,comment) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(report_id,employee_id) DO UPDATE SET project_id=excluded.project_id,work_date=excluded.work_date,attendance_status=excluded.attendance_status,regular_hours=excluded.regular_hours,overtime_hours=excluded.overtime_hours,comment=excluded.comment,updated_at=CURRENT_TIMESTAMP`);
  for(const entry of input.attendance)upsert.run(reportId,entry.employeeId,input.projectId,input.date,entry.status,entry.regularHours,entry.overtimeHours,entry.comment);
  return reportId;
}
export function approveDailyReport(id:number,approverId:number){return db.prepare(`UPDATE reports SET status='Approved',approved_by_id=?,approved_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='Submitted'`).run(approverId,id);}
export function deleteDraftReport(id:number){const report=getReport(id);return{changes:deleteDraftReportRecords(db,id),report};}
export function listAttendanceForReport(reportId:number):AttendanceEntry[]{return db.prepare(`SELECT a.id,a.report_id AS reportId,a.employee_id AS employeeId,e.name AS employeeName,e.role AS position,a.project_id AS projectId,p.name AS projectName,a.work_date AS date,a.attendance_status AS status,a.regular_hours AS regularHours,a.overtime_hours AS overtimeHours,a.comment FROM attendance_entries a JOIN employees e ON e.id=a.employee_id JOIN projects p ON p.id=a.project_id WHERE a.report_id=? ORDER BY e.name`).all(reportId) as unknown as AttendanceEntry[];}
export function listAttendance(period:string,projectId="",employeeId=""):AttendanceEntry[]{const params:string[]=[`${period}-%`];let where="a.work_date LIKE ?";if(projectId){where+=" AND a.project_id=?";params.push(projectId);}if(employeeId){where+=" AND a.employee_id=?";params.push(employeeId);}return db.prepare(`SELECT a.id,a.report_id AS reportId,a.employee_id AS employeeId,e.name AS employeeName,e.role AS position,a.project_id AS projectId,p.name AS projectName,a.work_date AS date,a.attendance_status AS status,a.regular_hours AS regularHours,a.overtime_hours AS overtimeHours,a.comment FROM attendance_entries a JOIN employees e ON e.id=a.employee_id JOIN projects p ON p.id=a.project_id WHERE ${where} ORDER BY e.name,a.work_date,a.id`).all(...params) as unknown as AttendanceEntry[];}
export function listSuspiciousAttendance(period:string){return db.prepare(`SELECT employee_id AS employeeId,work_date AS date,COUNT(DISTINCT project_id) AS projectCount,ROUND(SUM(regular_hours+overtime_hours),2) AS totalHours FROM attendance_entries WHERE work_date LIKE ? GROUP BY employee_id,work_date HAVING projectCount>1 OR totalHours>16 ORDER BY work_date,employee_id`).all(`${period}-%`) as unknown as {employeeId:string;date:string;projectCount:number;totalHours:number}[];}
export function getTimesheetPeriod(period:string):TimesheetPeriod{return db.prepare(`SELECT period,status,reviewed_by_id AS reviewedById,reviewed_at AS reviewedAt,closed_by_id AS closedById,closed_at AS closedAt FROM timesheet_periods WHERE period=?`).get(period) as TimesheetPeriod|undefined??{period,status:"Open",reviewedById:null,reviewedAt:"",closedById:null,closedAt:""};}
export function setTimesheetPeriodStatus(period:string,status:string,userId:number){db.prepare(`INSERT INTO timesheet_periods(period,status,reviewed_by_id,reviewed_at,closed_by_id,closed_at) VALUES(?,?,CASE WHEN ?='Reviewed' THEN ? END,CASE WHEN ?='Reviewed' THEN CURRENT_TIMESTAMP ELSE '' END,CASE WHEN ?='Closed' THEN ? END,CASE WHEN ?='Closed' THEN CURRENT_TIMESTAMP ELSE '' END) ON CONFLICT(period) DO UPDATE SET status=excluded.status,reviewed_by_id=CASE WHEN excluded.status='Reviewed' THEN excluded.reviewed_by_id ELSE timesheet_periods.reviewed_by_id END,reviewed_at=CASE WHEN excluded.status='Reviewed' THEN CURRENT_TIMESTAMP ELSE timesheet_periods.reviewed_at END,closed_by_id=CASE WHEN excluded.status='Closed' THEN excluded.closed_by_id ELSE timesheet_periods.closed_by_id END,closed_at=CASE WHEN excluded.status='Closed' THEN CURRENT_TIMESTAMP ELSE timesheet_periods.closed_at END`).run(period,status,status,userId,status,status,userId,status);}

const elementSelect=`SELECT e.id,e.project_id AS projectId,p.name AS projectName,e.code,e.element_type AS elementType,e.floor,e.zone,e.drawing_ref AS drawingRef,e.description,e.weight,e.length,e.width,e.height,e.supplier,e.planned_delivery_date AS plannedDeliveryDate,e.actual_delivery_date AS actualDeliveryDate,e.installation_date AS installationDate,e.status,e.issue_note AS issueNote,e.notes,e.active,e.installed_report_id AS installedReportId,e.created_at AS createdAt,e.updated_at AS updatedAt,e.created_import_id AS createdImportId,e.last_import_id AS lastImportId,e.last_source_revision AS lastSourceRevision,e.source_presence AS sourcePresence,e.source_key AS sourceKey,e.source_row AS sourceRow,e.installation_zone_id AS installationZoneId,COALESCE(iz.name,'') AS installationZoneName FROM project_elements e JOIN projects p ON p.id=e.project_id LEFT JOIN installation_zones iz ON iz.id=e.installation_zone_id`;
export function listProjectElements(projectId:string,filters:{q?:string;floor?:string;zone?:string;type?:string;status?:string;available?:boolean;installationZoneId?:number;unassignedZone?:boolean}={}):ProjectElement[]{const where=["e.project_id=?","e.active=1"],params:(string|number)[]=[projectId];if(filters.q){where.push("(e.code LIKE ? OR e.drawing_ref LIKE ?)");params.push(`%${filters.q}%`,`%${filters.q}%`);}if(filters.floor){where.push("e.floor=?");params.push(filters.floor);}if(filters.zone){where.push("e.zone=?");params.push(filters.zone);}if(filters.type){where.push("e.element_type=?");params.push(filters.type);}if(filters.status){where.push("e.status=?");params.push(filters.status);}if(filters.available)where.push("e.status IN ('Planned','Expected','Delivered','On site')");if(filters.unassignedZone)where.push("e.installation_zone_id IS NULL");else if(filters.installationZoneId){where.push("e.installation_zone_id=?");params.push(filters.installationZoneId);}return (db.prepare(`${elementSelect} WHERE ${where.join(" AND ")}`).all(...params) as unknown as ProjectElement[]).sort(compareElementsByMark);}
export function getProjectElement(id:number):ProjectElement|undefined{return db.prepare(`${elementSelect} WHERE e.id=?`).get(id) as ProjectElement|undefined;}
export function listElementHistory(elementId:number):ElementHistory[]{return db.prepare(`SELECT id,element_id AS elementId,from_status AS fromStatus,to_status AS toStatus,event_date AS eventDate,report_id AS reportId,actor_user_id AS actorUserId,actor,note,created_at AS createdAt FROM element_status_history WHERE element_id=? ORDER BY created_at DESC,id DESC`).all(elementId) as unknown as ElementHistory[];}
export type ProjectElementInput=Omit<ProjectElement,"id"|"projectName"|"active"|"installedReportId"|"createdAt"|"updatedAt"|"installationDate"|"createdImportId"|"lastImportId"|"lastSourceRevision"|"sourcePresence"|"sourceKey"|"sourceRow"|"installationZoneId"|"installationZoneName">&{id?:number;installationDate?:string};
export function saveProjectElement(input:ProjectElementInput,actor:{id:number;name:string}){if(input.id){const current=getProjectElement(input.id);if(!current||current.projectId!==input.projectId)throw new Error("Element not found.");const result=db.prepare(`UPDATE project_elements SET code=?,element_type=?,floor=?,zone=?,drawing_ref=?,description=?,weight=?,length=?,width=?,height=?,supplier=?,planned_delivery_date=?,actual_delivery_date=?,status=?,issue_note=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?`).run(input.code,input.elementType,input.floor,input.zone,input.drawingRef,input.description,input.weight,input.length,input.width,input.height,input.supplier,input.plannedDeliveryDate,input.actualDeliveryDate,input.status,input.issueNote,input.notes,input.id,input.projectId);if(current.status!==input.status)recordElementHistory(input.id,current.status,input.status,input.actualDeliveryDate||"",null,actor,input.issueNote||input.notes);return Number(result.changes);}const result=db.prepare(`INSERT INTO project_elements(project_id,code,element_type,floor,zone,drawing_ref,description,weight,length,width,height,supplier,planned_delivery_date,actual_delivery_date,status,issue_note,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.projectId,input.code,input.elementType,input.floor,input.zone,input.drawingRef,input.description,input.weight,input.length,input.width,input.height,input.supplier,input.plannedDeliveryDate,input.actualDeliveryDate,input.status,input.issueNote,input.notes);const id=Number(result.lastInsertRowid);recordElementHistory(id,"","Planned","",null,actor,"Created manually");return id;}
export function archiveProjectElement(id:number,actor:{id:number;name:string}){const element=getProjectElement(id);if(!element||element.installedReportId)throw new Error("Elements with installation history cannot be archived.");db.prepare(`UPDATE project_elements SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(id);recordElementHistory(id,element.status,"Archived","",null,actor,"Archived");}
export function recordElementHistory(elementId:number,fromStatus:string,toStatus:string,eventDate:string,reportId:number|null,actor:{id:number;name:string},note:string){db.prepare(`INSERT INTO element_status_history(element_id,from_status,to_status,event_date,report_id,actor_user_id,actor,note) VALUES(?,?,?,?,?,?,?,?)`).run(elementId,fromStatus,toStatus,eventDate,reportId,actor.id,actor.name,note);}
export function listReportElements(reportId:number):ProjectElement[]{return (db.prepare(`${elementSelect} JOIN daily_report_elements re ON re.element_id=e.id WHERE re.report_id=?`).all(reportId) as unknown as ProjectElement[]).sort(compareElementsByMark);}
export function syncReportElements(reportId:number,projectId:string,elementIds:number[]){const unique=[...new Set(elementIds)];for(const id of unique){const row=db.prepare(`SELECT e.project_id AS projectId,e.status,re.report_id AS linkedReport FROM project_elements e LEFT JOIN daily_report_elements re ON re.element_id=e.id AND re.finalized_at<>'' WHERE e.id=? AND e.active=1`).get(id) as {projectId:string;status:string;linkedReport:number|null}|undefined;if(!row||row.projectId!==projectId||!["Planned","Expected","Delivered","On site"].includes(row.status)||row.linkedReport)throw new Error("Selected element is no longer available for installation.");}db.prepare(`DELETE FROM daily_report_elements WHERE report_id=? AND finalized_at=''`).run(reportId);const insert=db.prepare(`INSERT INTO daily_report_elements(report_id,element_id) VALUES(?,?)`);for(const id of unique)insert.run(reportId,id);}
export function finalizeReportElements(reportId:number,date:string,actor:{id:number;name:string}){const rows=db.prepare(`SELECT e.id,e.status FROM daily_report_elements re JOIN project_elements e ON e.id=re.element_id JOIN reports r ON r.id=re.report_id WHERE re.report_id=? AND re.finalized_at='' AND e.project_id=r.project_id`).all(reportId) as {id:number;status:string}[];for(const row of rows){const result=db.prepare(`UPDATE project_elements SET status='Installed',installation_date=?,installed_report_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND active=1 AND status IN ('Planned','Expected','Delivered','On site') AND installed_report_id IS NULL`).run(date,reportId,row.id);if(result.changes!==1)throw new Error("An element was already installed or is blocked.");db.prepare(`UPDATE daily_report_elements SET finalized_at=CURRENT_TIMESTAMP WHERE report_id=? AND element_id=?`).run(reportId,row.id);recordElementHistory(row.id,row.status,"Installed",date,reportId,actor,`Installed through Daily Report #${reportId}`);}}
export function correctInstalledElement(id:number,nextStatus:string,note:string,actor:{id:number;name:string}){const element=getProjectElement(id);if(!element||element.status!=="Installed"||!["On site","Issue","Rejected / Hold"].includes(nextStatus)||!note)throw new Error("Invalid installation correction.");db.prepare(`UPDATE project_elements SET status=?,installation_date='',installed_report_id=NULL,issue_note=CASE WHEN ? IN ('Issue','Rejected / Hold') THEN ? ELSE issue_note END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='Installed'`).run(nextStatus,nextStatus,note,id);recordElementHistory(id,"Installed",nextStatus,"",element.installedReportId,actor,note);}

export function setProjectCoordinates(projectId:string,latitude:number|null,longitude:number|null){return db.prepare("UPDATE projects SET latitude=?,longitude=? WHERE id=?").run(latitude,longitude,projectId);}
// Physical erection progress from the immutable element register: installed elements over
// applicable elements (active, excluding 'Replaced'). The authoritative progress source —
// never derived from loads/deliveries/reports counts.
export function projectErectionProgress(projectId:string):{installed:number;total:number}{const row=db.prepare("SELECT SUM(CASE WHEN status='Installed' THEN 1 ELSE 0 END) installed, SUM(CASE WHEN status<>'Replaced' THEN 1 ELSE 0 END) total FROM project_elements WHERE project_id=? AND active=1").get(projectId) as {installed:number|null;total:number|null};return {installed:Number(row.installed||0),total:Number(row.total||0)};}
// The next delivery for a project = the earliest still-upcoming Planned load (Cancelled and
// already-received Accepted loads excluded). Deterministic on date, then time, then number.
export function nextProjectDelivery(projectId:string,today:string):LoadSummary|null{return listProjectLoadSummaries(projectId,false).filter((load)=>load.status==="Planned"&&load.plannedDate&&load.plannedDate>=today).sort((a,b)=>(a.plannedDate===b.plannedDate?(a.plannedTime<b.plannedTime?-1:a.plannedTime>b.plannedTime?1:a.loadNumber-b.loadNumber):(a.plannedDate<b.plannedDate?-1:1)))[0]??null;}
export function listReportWeather(reportId:number):ReportWeather[]{return db.prepare(`SELECT id,report_id AS reportId,timepoint,temperature,condition_code AS conditionCode,condition,precipitation,wind_speed AS windSpeed,wind_gust AS windGust,provider,retrieved_at AS retrievedAt FROM daily_report_weather WHERE report_id=? ORDER BY timepoint`).all(reportId) as unknown as ReportWeather[];}
export function replaceReportWeather(reportId:number,rows:Omit<ReportWeather,"id"|"reportId">[]){db.prepare("DELETE FROM daily_report_weather WHERE report_id=?").run(reportId);const insert=db.prepare(`INSERT INTO daily_report_weather(report_id,timepoint,temperature,condition_code,condition,precipitation,wind_speed,wind_gust,provider,retrieved_at) VALUES(?,?,?,?,?,?,?,?,?,?)`);for(const row of rows)insert.run(reportId,row.timepoint,row.temperature,row.conditionCode,row.condition,row.precipitation,row.windSpeed,row.windGust,row.provider,row.retrievedAt);}
export function createElementImport(input:Omit<ElementImport,"id"|"importedAt"|"appliedAt"|"sourcePayloadJson"|"appliedById"|"appliedBy">){const result=db.prepare(`INSERT INTO element_register_imports(project_id,original_filename,source_revision,source_hash,worksheet_name,mapping_json,payload_json,source_payload_json,summary_json,status,notes,imported_by_id,imported_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.projectId,input.originalFilename,input.sourceRevision,input.sourceHash,input.worksheetName,input.mappingJson,input.payloadJson,input.payloadJson,input.summaryJson,input.status,input.notes,input.importedById,input.importedBy);return Number(result.lastInsertRowid);}
export function prepareElementImport(id:number,projectId:string,input:{worksheetName:string;mappingJson:string;payloadJson:string;summaryJson:string}){const result=db.prepare("UPDATE element_register_imports SET worksheet_name=?,mapping_json=?,payload_json=?,summary_json=?,status='Preview' WHERE id=? AND project_id=? AND status IN ('Mapping','Preview')").run(input.worksheetName,input.mappingJson,input.payloadJson,input.summaryJson,id,projectId);if(result.changes!==1)throw new Error("Import review session is no longer available.");}
export function persistElementImportReview(id:number,projectId:string,worksheetName:string,mappingJson:string){const result=db.prepare("UPDATE element_register_imports SET worksheet_name=?,mapping_json=?,status='Mapping' WHERE id=? AND project_id=? AND status IN ('Mapping','Preview')").run(worksheetName,mappingJson,id,projectId);if(result.changes!==1)throw new Error("Import review session is no longer available.");}
export function getElementImport(id:number):ElementImport|undefined{return db.prepare(`SELECT id,project_id AS projectId,original_filename AS originalFilename,source_revision AS sourceRevision,source_hash AS sourceHash,worksheet_name AS worksheetName,mapping_json AS mappingJson,payload_json AS payloadJson,source_payload_json AS sourcePayloadJson,summary_json AS summaryJson,status,notes,imported_by_id AS importedById,imported_by AS importedBy,imported_at AS importedAt,applied_at AS appliedAt,applied_by_id AS appliedById,applied_by AS appliedBy FROM element_register_imports WHERE id=?`).get(id) as ElementImport|undefined;}
export function listElementImports(projectId:string):ElementImport[]{return db.prepare(`SELECT id,project_id AS projectId,original_filename AS originalFilename,source_revision AS sourceRevision,source_hash AS sourceHash,worksheet_name AS worksheetName,mapping_json AS mappingJson,payload_json AS payloadJson,source_payload_json AS sourcePayloadJson,summary_json AS summaryJson,status,notes,imported_by_id AS importedById,imported_by AS importedBy,imported_at AS importedAt,applied_at AS appliedAt,applied_by_id AS appliedById,applied_by AS appliedBy FROM element_register_imports WHERE project_id=? ORDER BY imported_at DESC,id DESC`).all(projectId) as unknown as ElementImport[];}
export function hasAppliedElementImport(projectId:string,sourceHash:string){return Boolean(db.prepare("SELECT 1 FROM element_register_imports WHERE project_id=? AND source_hash=? AND status='Applied'").get(projectId,sourceHash));}
export function getAppliedElementImport(projectId:string,sourceHash:string):ElementImport|undefined{const row=db.prepare("SELECT id FROM element_register_imports WHERE project_id=? AND source_hash=? AND status='Applied' ORDER BY applied_at,id LIMIT 1").get(projectId,sourceHash) as {id:number}|undefined;return row?getElementImport(row.id):undefined;}
export function beginElementImportApply(id:number,projectId:string){return db.prepare("UPDATE element_register_imports SET status='Applying' WHERE id=? AND project_id=? AND status='Preview'").run(id,projectId);}
export function applyElementImport(importId:number,projectId:string,sourceRevision:string,rows:Array<{row?:number;matchedElementId?:number;code:string;elementType:string;floor:string;zone:string;drawingRef:string;description:string;weight:number|null;length:number|null;width:number|null;height:number|null;supplier:string;plannedDeliveryDate:string}>,missingDecisions:Record<string,string>,actor:{id:number;name:string}){const existing=listProjectElements(projectId),byId=new Map(existing.map((row)=>[row.id,row])),matchedIds=new Set<number>();for(const row of rows){const current=row.matchedElementId?byId.get(row.matchedElementId):undefined;if(current){if(current.projectId!==projectId||matchedIds.has(current.id))throw new Error("Invalid or ambiguous element identity match.");matchedIds.add(current.id);db.prepare(`UPDATE project_elements SET element_type=?,floor=?,zone=?,drawing_ref=?,description=?,weight=?,length=?,width=?,height=?,supplier=?,planned_delivery_date=?,last_import_id=?,last_source_revision=?,source_presence='Present',source_row=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?`).run(row.elementType,row.floor,row.zone,row.drawingRef,row.description,row.weight,row.length,row.width,row.height,row.supplier,row.plannedDeliveryDate,importId,sourceRevision,row.row??null,current.id,projectId);}else{const result=db.prepare(`INSERT INTO project_elements(project_id,code,element_type,floor,zone,drawing_ref,description,weight,length,width,height,supplier,planned_delivery_date,status,created_import_id,last_import_id,last_source_revision,source_presence,source_row) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'Planned',?,?,?,'Present',?)`).run(projectId,row.code,row.elementType,row.floor,row.zone,row.drawingRef,row.description,row.weight,row.length,row.width,row.height,row.supplier,row.plannedDeliveryDate,importId,importId,sourceRevision,row.row??null);recordElementHistory(Number(result.lastInsertRowid),"","Planned","",null,actor,"Imported from XLSX synchronization");}}
  for(const current of existing.filter((row)=>!matchedIds.has(row.id))){const decision=missingDecisions[String(current.id)]??"Keep";if(decision==="Supersede"&&current.status!=="Installed"&&current.installedReportId===null){db.prepare("UPDATE project_elements SET source_presence='Missing',active=0,last_import_id=?,last_source_revision=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?").run(importId,sourceRevision,current.id,projectId);recordElementHistory(current.id,current.status,"Source removed","",null,actor,"Marked superseded by register synchronization");}else db.prepare("UPDATE project_elements SET source_presence='Missing',last_import_id=?,last_source_revision=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?").run(importId,sourceRevision,current.id,projectId);}
  const completed=db.prepare("UPDATE element_register_imports SET status='Applied',applied_at=CURRENT_TIMESTAMP,applied_by_id=?,applied_by=? WHERE id=? AND project_id=? AND status='Applying'").run(actor.id,actor.name,importId,projectId);if(completed.changes!==1)throw new Error("Synchronization lifecycle changed during apply.");
}
export function bulkUpdateElementStatus(projectId:string,ids:number[],nextStatus:string,operationDate:string,actor:{id:number;name:string}){if(!["Expected","Delivered","On site"].includes(nextStatus))throw new Error("Invalid bulk status.");const unique=[...new Set(ids)];if(unique.length!==ids.length||!unique.length)throw new Error("Invalid element selection.");const rows=unique.map((id)=>getProjectElement(id));if(rows.some((row)=>!row||row.projectId!==projectId))throw new Error("Element project scope mismatch.");let changed=0;for(const row of rows){if(!row||row.status==="Installed"||row.installedReportId!==null||["Issue","Rejected / Hold","Replaced"].includes(row.status))throw new Error("Selected element requires individual review.");if(row.status===nextStatus)continue;db.prepare("UPDATE project_elements SET status=?,actual_delivery_date=CASE WHEN ? IN ('Delivered','On site') AND actual_delivery_date='' THEN ? ELSE actual_delivery_date END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND status<>'Installed' AND installed_report_id IS NULL").run(nextStatus,nextStatus,operationDate,row.id,projectId);recordElementHistory(row.id,row.status,nextStatus,"",null,actor,"Bulk operational status update");changed++;}return changed;}

export type ProjectPermissionRow={userId:number;projectId:string;capabilities:CapabilityMap;grantedById:number|null;grantedAt:string;updatedAt:string};
const permissionSelect=`SELECT user_id AS userId,project_id AS projectId,capabilities_json AS capabilitiesJson,granted_by_id AS grantedById,granted_at AS grantedAt,updated_at AS updatedAt FROM project_permissions`;
function toPermissionRow(row:{userId:number;projectId:string;capabilitiesJson:string;grantedById:number|null;grantedAt:string;updatedAt:string}):ProjectPermissionRow{let capabilities:CapabilityMap={};try{capabilities=sanitizeCapabilityMap(JSON.parse(row.capabilitiesJson||"{}") as Record<string,unknown>);}catch{capabilities={};}return{userId:row.userId,projectId:row.projectId,capabilities,grantedById:row.grantedById,grantedAt:row.grantedAt,updatedAt:row.updatedAt};}
export function getProjectPermission(userId:number,projectId:string):ProjectPermissionRow|undefined{const row=db.prepare(`${permissionSelect} WHERE user_id=? AND project_id=?`).get(userId,projectId) as Parameters<typeof toPermissionRow>[0]|undefined;return row?toPermissionRow(row):undefined;}
export function listUserProjectPermissions(userId:number):ProjectPermissionRow[]{return (db.prepare(`${permissionSelect} WHERE user_id=?`).all(userId) as Parameters<typeof toPermissionRow>[0][]).map(toPermissionRow);}
export function listProjectPermissions(projectId:string):ProjectPermissionRow[]{return (db.prepare(`${permissionSelect} WHERE project_id=?`).all(projectId) as Parameters<typeof toPermissionRow>[0][]).map(toPermissionRow);}
export function setProjectPermission(userId:number,projectId:string,capabilities:CapabilityMap,grantedById:number){return db.prepare(`INSERT INTO project_permissions(user_id,project_id,capabilities_json,granted_by_id) VALUES(?,?,?,?) ON CONFLICT(user_id,project_id) DO UPDATE SET capabilities_json=excluded.capabilities_json,granted_by_id=excluded.granted_by_id,updated_at=CURRENT_TIMESTAMP`).run(userId,projectId,JSON.stringify(capabilities),grantedById);}
export function removeProjectPermission(userId:number,projectId:string){return db.prepare("DELETE FROM project_permissions WHERE user_id=? AND project_id=?").run(userId,projectId);}
export function archiveProject(id:string,userId:number){return db.prepare("UPDATE projects SET archived_at=CURRENT_TIMESTAMP,archived_by_id=? WHERE id=? AND archived_at=''").run(userId,id);}
export function restoreProject(id:string){return db.prepare("UPDATE projects SET archived_at='',archived_by_id=NULL WHERE id=? AND archived_at<>''").run(id);}

// Employee lifecycle. A hard delete is only safe when no protected history references
// the employee; otherwise the employee must be archived (status Inactive) instead.
export function employeeProtectedHistoryCount(id:string):number{
  const q=(sql:string)=>Number((db.prepare(sql).get(id) as {c:number}).c);
  return q("SELECT COUNT(*) AS c FROM attendance_entries WHERE employee_id=?")
    +q("SELECT COUNT(*) AS c FROM employee_project_assignments WHERE employee_id=?")
    +q("SELECT COUNT(*) AS c FROM reports WHERE reporter_employee_id=?")
    +q("SELECT COUNT(*) AS c FROM project_members WHERE employee_id=?")
    +q("SELECT COUNT(*) AS c FROM projects WHERE manager_employee_id=?");
}
export function deleteEmployee(id:string){return db.prepare("DELETE FROM employees WHERE id=?").run(id);}
export function restoreEmployee(id:string){return db.prepare("UPDATE employees SET employment_status='Active',employment_end_date='' WHERE id=?").run(id);}

// ---- Sprint 12 Improvement Pack: Installation Zones ----
// Operational grouping of physical elements for erection. Separate from the design `zone`
// so an XLSX re-sync never overwrites it. Assignment writes only installation_zone_id and
// never element status/history.
export type InstallationZone={id:number;projectId:string;name:string;description:string;sortOrder:number;active:number;elementCount:number};
export function listInstallationZones(projectId:string):InstallationZone[]{return db.prepare("SELECT z.id,z.project_id AS projectId,z.name,z.description,z.sort_order AS sortOrder,z.active,(SELECT COUNT(*) FROM project_elements e WHERE e.installation_zone_id=z.id AND e.active=1) AS elementCount FROM installation_zones z WHERE z.project_id=? AND z.active=1 ORDER BY z.sort_order,z.name").all(projectId) as unknown as InstallationZone[];}
export function getInstallationZone(id:number):InstallationZone|undefined{return db.prepare("SELECT z.id,z.project_id AS projectId,z.name,z.description,z.sort_order AS sortOrder,z.active,0 AS elementCount FROM installation_zones z WHERE z.id=?").get(id) as InstallationZone|undefined;}
export function createInstallationZone(projectId:string,name:string,description:string):number{const trimmed=name.trim();if(!trimmed)throw new Error("Installation zone name is required.");const next=Number((db.prepare("SELECT COALESCE(MAX(sort_order),0)+1 AS n FROM installation_zones WHERE project_id=?").get(projectId) as {n:number}).n);const result=db.prepare("INSERT INTO installation_zones(project_id,name,description,sort_order) VALUES(?,?,?,?)").run(projectId,trimmed,description.trim(),next);return Number(result.lastInsertRowid);}
export function renameInstallationZone(id:number,projectId:string,name:string,description:string){const trimmed=name.trim();if(!trimmed)throw new Error("Installation zone name is required.");const result=db.prepare("UPDATE installation_zones SET name=?,description=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND active=1").run(trimmed,description.trim(),id,projectId);if(result.changes!==1)throw new Error("Installation zone not found.");}
// Soft delete: deactivate the zone and detach it from every element. Element identity and
// status are untouched — only the operational grouping link is cleared.
export function deleteInstallationZone(id:number,projectId:string){const result=db.prepare("UPDATE installation_zones SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND active=1").run(id,projectId);if(result.changes!==1)throw new Error("Installation zone not found.");db.prepare("UPDATE project_elements SET installation_zone_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE installation_zone_id=? AND project_id=?").run(id,projectId);}
// Bulk-assign (or clear, zoneId=null) an installation zone on a set of elements. Validates
// project scope for both the elements and the zone. Returns the number of rows changed.
export function assignElementsToInstallationZone(projectId:string,ids:number[],zoneId:number|null):number{const unique=[...new Set(ids)];if(!unique.length)throw new Error("No elements selected.");const rows=unique.map((id)=>getProjectElement(id));if(rows.some((row)=>!row||row.projectId!==projectId||!row.active))throw new Error("Element project scope mismatch.");if(zoneId!==null){const zone=getInstallationZone(zoneId);if(!zone||zone.projectId!==projectId||!zone.active)throw new Error("Installation zone project scope mismatch.");}let changed=0;const stmt=db.prepare("UPDATE project_elements SET installation_zone_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND active=1");for(const row of rows){if(!row)continue;if(row.installationZoneId===zoneId)continue;stmt.run(zoneId,row.id,projectId);changed++;}return changed;}

// ---- Sprint 12: Load Planning ----
export type TransportProfile={id:number;name:string;active:number;rank:number;maxPayloadT:number|null;maxLengthMm:number|null;maxWidthMm:number|null;maxHeightMm:number|null;placeholder:number;note:string};
export type Load={id:number;projectId:string;loadNumber:number;status:string;plannedDate:string;plannedTime:string;transportProfileId:number|null;recommendedProfileId:number|null;loadingDirection:string;orientationNote:string;note:string;exceptionAck:number;exceptionAckById:number|null;exceptionAckAt:string;exceptionReason:string;weekendAck:number;weekendAckById:number|null;weekendAckAt:string;acceptanceType:string;acceptedAt:string;acceptedById:number|null;acceptedBy:string;createdById:number|null;createdBy:string;createdAt:string;updatedAt:string};
export type LoadSummary=Load&{elementCount:number;totalWeightT:number;receivedCount:number;installedCount:number};
export type LoadElementRow={id:number;loadId:number;elementId:number;position:number;orientation:string;intent:string;note:string;code:string;elementType:string;floor:string;zone:string;installationZoneName:string;weight:number|null;length:number|null;width:number|null;height:number|null;status:string};
export type LoadElementInput={elementId:number;position:number;orientation:string;intent:string;note:string};

const transportProfileSelect=`SELECT id,name,active,rank,max_payload_t AS maxPayloadT,max_length_mm AS maxLengthMm,max_width_mm AS maxWidthMm,max_height_mm AS maxHeightMm,placeholder,note FROM transport_profiles`;
export function listTransportProfiles():TransportProfile[]{return db.prepare(`${transportProfileSelect} ORDER BY rank,id`).all() as unknown as TransportProfile[];}
export function getTransportProfile(id:number):TransportProfile|undefined{return db.prepare(`${transportProfileSelect} WHERE id=?`).get(id) as TransportProfile|undefined;}

const loadSelect=`SELECT id,project_id AS projectId,load_number AS loadNumber,status,planned_date AS plannedDate,planned_time AS plannedTime,transport_profile_id AS transportProfileId,recommended_profile_id AS recommendedProfileId,loading_direction AS loadingDirection,orientation_note AS orientationNote,note,exception_ack AS exceptionAck,exception_ack_by_id AS exceptionAckById,exception_ack_at AS exceptionAckAt,exception_reason AS exceptionReason,weekend_ack AS weekendAck,weekend_ack_by_id AS weekendAckById,weekend_ack_at AS weekendAckAt,acceptance_type AS acceptanceType,accepted_at AS acceptedAt,accepted_by_id AS acceptedById,accepted_by AS acceptedBy,created_by_id AS createdById,created_by AS createdBy,created_at AS createdAt,updated_at AS updatedAt FROM loads`;
export function getLoad(id:number):Load|undefined{return db.prepare(`${loadSelect} WHERE id=?`).get(id) as Load|undefined;}
export function listProjectLoadSummaries(projectId:string,includeCancelled=false):LoadSummary[]{const cancelClause=includeCancelled?"":" AND l.status<>'Cancelled'";return db.prepare(`SELECT l.id,l.project_id AS projectId,l.load_number AS loadNumber,l.status,l.planned_date AS plannedDate,l.planned_time AS plannedTime,l.transport_profile_id AS transportProfileId,l.recommended_profile_id AS recommendedProfileId,l.loading_direction AS loadingDirection,l.orientation_note AS orientationNote,l.note,l.exception_ack AS exceptionAck,l.exception_ack_by_id AS exceptionAckById,l.exception_ack_at AS exceptionAckAt,l.exception_reason AS exceptionReason,l.weekend_ack AS weekendAck,l.weekend_ack_by_id AS weekendAckById,l.weekend_ack_at AS weekendAckAt,l.acceptance_type AS acceptanceType,l.accepted_at AS acceptedAt,l.accepted_by_id AS acceptedById,l.accepted_by AS acceptedBy,l.created_by_id AS createdById,l.created_by AS createdBy,l.created_at AS createdAt,l.updated_at AS updatedAt,(SELECT COUNT(*) FROM load_elements le WHERE le.load_id=l.id AND le.active_alloc=1) AS elementCount,COALESCE((SELECT ROUND(SUM(e.weight),3) FROM load_elements le JOIN project_elements e ON e.id=le.element_id WHERE le.load_id=l.id AND le.active_alloc=1),0) AS totalWeightT,COALESCE((SELECT COUNT(*) FROM load_receipt_elements lre WHERE lre.load_id=l.id AND lre.disposition IN ('received','added')),0) AS receivedCount,COALESCE((SELECT COUNT(*) FROM load_receipt_elements lre JOIN project_elements e ON e.id=lre.element_id WHERE lre.load_id=l.id AND lre.disposition IN ('received','added') AND e.status='Installed'),0) AS installedCount FROM loads l WHERE l.project_id=?${cancelClause} ORDER BY (l.planned_date=''),l.planned_date,l.planned_time,l.load_number`).all(projectId) as unknown as LoadSummary[];}
export function listLoadElements(loadId:number):LoadElementRow[]{return db.prepare(`SELECT le.id,le.load_id AS loadId,le.element_id AS elementId,le.position,le.orientation,le.intent,le.note,e.code,e.element_type AS elementType,e.floor,e.zone,COALESCE(iz.name,'') AS installationZoneName,e.weight,e.length,e.width,e.height,e.status FROM load_elements le JOIN project_elements e ON e.id=le.element_id LEFT JOIN installation_zones iz ON iz.id=e.installation_zone_id WHERE le.load_id=? ORDER BY le.position,le.id`).all(loadId) as unknown as LoadElementRow[];}
export function nextProjectLoadNumber(projectId:string):number{return Number((db.prepare("SELECT COALESCE(MAX(load_number),0)+1 AS n FROM loads WHERE project_id=?").get(projectId) as {n:number}).n);}
export function listActiveAllocatedElementIds(projectId:string,exceptLoadId=0):number[]{return (db.prepare("SELECT DISTINCT le.element_id AS elementId FROM load_elements le JOIN loads l ON l.id=le.load_id WHERE l.project_id=? AND l.status<>'Cancelled' AND le.active_alloc=1 AND le.load_id<>?").all(projectId,exceptLoadId) as {elementId:number}[]).map((row)=>row.elementId);}
export function createLoad(input:{projectId:string;loadNumber:number;status:string;plannedDate:string;plannedTime:string;transportProfileId:number|null;recommendedProfileId:number|null;loadingDirection:string;orientationNote:string;note:string;createdById:number;createdBy:string}):number{const result=db.prepare(`INSERT INTO loads(project_id,load_number,status,planned_date,planned_time,transport_profile_id,recommended_profile_id,loading_direction,orientation_note,note,created_by_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.projectId,input.loadNumber,input.status,input.plannedDate,input.plannedTime,input.transportProfileId,input.recommendedProfileId,input.loadingDirection,input.orientationNote,input.note,input.createdById,input.createdBy);return Number(result.lastInsertRowid);}
export function updateLoadDetails(id:number,projectId:string,input:{status:string;plannedDate:string;plannedTime:string;transportProfileId:number|null;recommendedProfileId:number|null;loadingDirection:string;orientationNote:string;note:string}){const current=db.prepare("SELECT status FROM loads WHERE id=? AND project_id=?").get(id,projectId) as {status:string}|undefined;if(current&&!["Draft","Planned"].includes(current.status))throw new Error("A received or cancelled load cannot be edited.");const result=db.prepare(`UPDATE loads SET status=?,planned_date=?,planned_time=?,transport_profile_id=?,recommended_profile_id=?,loading_direction=?,orientation_note=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?`).run(input.status,input.plannedDate,input.plannedTime,input.transportProfileId,input.recommendedProfileId,input.loadingDirection,input.orientationNote,input.note,id,projectId);if(result.changes!==1)throw new Error("Load not found.");}
export function replaceLoadElements(loadId:number,projectId:string,activeAlloc:number,elements:LoadElementInput[]){const load=db.prepare("SELECT status FROM loads WHERE id=? AND project_id=?").get(loadId,projectId) as {status:string}|undefined;if(load&&!["Draft","Planned"].includes(load.status))throw new Error("A received or cancelled load cannot be re-planned.");const ids=elements.map((element)=>element.elementId);if(new Set(ids).size!==ids.length)throw new Error("An element appears twice in the same load.");for(const element of elements){const row=db.prepare("SELECT project_id AS projectId,active FROM project_elements WHERE id=?").get(element.elementId) as {projectId:string;active:number}|undefined;if(!row||row.projectId!==projectId||!row.active)throw new Error("Selected element is not available for this project.");}const allocated=new Set(listActiveAllocatedElementIds(projectId,loadId));for(const id of ids)if(allocated.has(id))throw new Error("An element is already allocated to another active load.");db.prepare("DELETE FROM load_elements WHERE load_id=?").run(loadId);const insert=db.prepare("INSERT INTO load_elements(load_id,element_id,position,orientation,intent,note,active_alloc) VALUES(?,?,?,?,?,?,?)");for(const element of elements)insert.run(loadId,element.elementId,element.position,element.orientation,element.intent,element.note,activeAlloc);}
export function cancelLoad(id:number,projectId:string){const result=db.prepare("UPDATE loads SET status='Cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND status IN ('Draft','Planned')").run(id,projectId);if(result.changes!==1)throw new Error("Load cannot be cancelled. A received load is a physical delivery record.");db.prepare("UPDATE load_elements SET active_alloc=0 WHERE load_id=?").run(id);}

// Persist the weekend-delivery acknowledgement for a load (idempotent; stores actor + time
// when acknowledged, clears when not). Weekend delivery is a warning any planner may accept.
export function setLoadWeekendAck(id:number,projectId:string,acknowledged:boolean,actor:{id:number;name:string}){db.prepare("UPDATE loads SET weekend_ack=?,weekend_ack_by_id=?,weekend_ack_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE '' END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?").run(acknowledged?1:0,acknowledged?actor.id:null,acknowledged?1:0,id,projectId);}
// Archived projects are read-only; every load mutation must pass this first.
export function assertLoadMutationAllowed(projectId:string):Project{const project=getProject(projectId);if(!project)throw new Error("Project not found.");if(project.archivedAt)throw new Error("Archived projects are read-only. Restore the project first.");return project;}
export function acknowledgeLoadException(id:number,projectId:string,actor:{id:number;name:string},reason:string){const result=db.prepare("UPDATE loads SET exception_ack=1,exception_ack_by_id=?,exception_ack_at=CURRENT_TIMESTAMP,exception_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?").run(actor.id,reason,id,projectId);if(result.changes!==1)throw new Error("Load not found.");}

// ---- Sprint 12 Improvement Pack: Load → Delivery → Installation lifecycle ----
export type LoadReceipt={id:number;loadId:number;projectId:string;acceptanceType:string;comment:string;receivedCount:number;missingCount:number;addedCount:number;acceptedById:number|null;acceptedBy:string;acceptedAt:string};
export type LoadReceiptElement={id:number;receiptId:number;loadId:number;elementId:number;disposition:string;category:string;note:string;code:string;elementType:string;status:string};
export type LoadInstallationProgress={accepted:boolean;received:number;installed:number;onSite:number;missing:number;added:number;fullyInstalled:boolean};

export function getLoadReceipt(loadId:number):LoadReceipt|undefined{return db.prepare("SELECT id,load_id AS loadId,project_id AS projectId,acceptance_type AS acceptanceType,comment,received_count AS receivedCount,missing_count AS missingCount,added_count AS addedCount,accepted_by_id AS acceptedById,accepted_by AS acceptedBy,accepted_at AS acceptedAt FROM load_receipts WHERE load_id=? ORDER BY id DESC LIMIT 1").get(loadId) as LoadReceipt|undefined;}
export function listLoadReceiptElements(receiptId:number):LoadReceiptElement[]{return db.prepare("SELECT lre.id,lre.receipt_id AS receiptId,lre.load_id AS loadId,lre.element_id AS elementId,lre.disposition,lre.category,lre.note,e.code,e.element_type AS elementType,e.status FROM load_receipt_elements lre JOIN project_elements e ON e.id=lre.element_id WHERE lre.receipt_id=? ORDER BY CASE lre.disposition WHEN 'received' THEN 0 WHEN 'added' THEN 1 ELSE 2 END,lre.id").all(receiptId) as unknown as LoadReceiptElement[];}

// Installation progress DERIVED from current element status against the ACTUAL received
// composition (received + added), never a stored mutable field. Installation itself remains
// a Daily-Report fact: an element becomes 'Installed' only through an approved Daily Report.
export function loadInstallationProgress(loadId:number):LoadInstallationProgress{const receipt=getLoadReceipt(loadId);if(!receipt)return{accepted:false,received:0,installed:0,onSite:0,missing:0,added:0,fullyInstalled:false};const row=db.prepare("SELECT SUM(CASE WHEN lre.disposition IN ('received','added') THEN 1 ELSE 0 END) received,SUM(CASE WHEN lre.disposition IN ('received','added') AND e.status='Installed' THEN 1 ELSE 0 END) installed,SUM(CASE WHEN lre.disposition='missing' THEN 1 ELSE 0 END) missing,SUM(CASE WHEN lre.disposition='added' THEN 1 ELSE 0 END) added FROM load_receipt_elements lre JOIN project_elements e ON e.id=lre.element_id WHERE lre.load_id=?").get(loadId) as {received:number|null;installed:number|null;missing:number|null;added:number|null};const received=Number(row.received||0),installed=Number(row.installed||0);return{accepted:true,received,installed,onSite:received-installed,missing:Number(row.missing||0),added:Number(row.added||0),fullyInstalled:received>0&&installed===received};}

// Accept ("receive") a planned load, recording the ACTUAL received composition in an
// append-only receipt. as_planned = every planned element received. with_discrepancies =
// caller classifies every planned element as received or missing and may add extra elements
// that physically arrived. Missing elements are released for re-planning; received/added
// elements become 'On site' (with element history). Physical receipt is a legitimate status
// change — distinct from load *planning*, which never touches element status. Not nestable-
// safe on its own: callers must wrap this in runTransaction.
export function acceptLoad(loadId:number,projectId:string,actor:{id:number;name:string},input:{acceptanceType:"as_planned"|"with_discrepancies";comment:string;operationDate:string;received:number[];missing:number[];added:Array<{elementId:number;category:string;note:string}>}):number{
  const load=getLoad(loadId);
  if(!load||load.projectId!==projectId)throw new Error("Load not found.");
  if(load.status!=="Planned")throw new Error("Only a planned load can be received.");
  const plannedIds=new Set(listLoadElements(loadId).map((row)=>row.elementId));
  let received:number[],missing:number[];
  const added=input.acceptanceType==="with_discrepancies"?(input.added??[]):[];
  if(input.acceptanceType==="as_planned"){
    received=[...plannedIds];missing=[];
  }else{
    received=[...new Set(input.received)];missing=[...new Set(input.missing)];
    for(const id of received)if(!plannedIds.has(id))throw new Error("A received element was not part of the plan.");
    for(const id of missing)if(!plannedIds.has(id))throw new Error("A missing element was not part of the plan.");
    if(received.some((id)=>missing.includes(id)))throw new Error("An element cannot be both received and missing.");
    const classified=new Set([...received,...missing]);
    if(classified.size!==plannedIds.size)throw new Error("Every planned element must be marked received or missing.");
  }
  // Validate added elements: real, active, this project, available, not planned here, not
  // reserved by another active load, not already installed.
  const allocatedElsewhere=new Set(listActiveAllocatedElementIds(projectId,loadId));
  const addedSeen=new Set<number>();
  for(const item of added){
    const element=getProjectElement(item.elementId);
    if(!element||element.projectId!==projectId||!element.active)throw new Error("An added element is not available for this project.");
    if(plannedIds.has(item.elementId))throw new Error("An added element is already part of the plan.");
    if(allocatedElsewhere.has(item.elementId))throw new Error("An added element is allocated to another active load.");
    if(addedSeen.has(item.elementId))throw new Error("An element was added twice.");
    if(element.status==="Installed"||element.installedReportId!==null)throw new Error("An added element is already installed.");
    addedSeen.add(item.elementId);
  }
  const receiptId=Number(db.prepare("INSERT INTO load_receipts(load_id,project_id,acceptance_type,comment,received_count,missing_count,added_count,accepted_by_id,accepted_by) VALUES(?,?,?,?,?,?,?,?,?)").run(loadId,projectId,input.acceptanceType,input.comment,received.length+added.length,missing.length,added.length,actor.id,actor.name).lastInsertRowid);
  const insReceiptEl=db.prepare("INSERT INTO load_receipt_elements(receipt_id,load_id,element_id,disposition,category,note) VALUES(?,?,?,?,?,?)");
  for(const id of received)insReceiptEl.run(receiptId,loadId,id,"received","","");
  for(const id of missing)insReceiptEl.run(receiptId,loadId,id,"missing","","");
  for(const item of added)insReceiptEl.run(receiptId,loadId,item.elementId,"added",item.category||"",item.note||"");
  // Attach added elements to the load composition (reserved) after the current max position.
  let pos=Number((db.prepare("SELECT COALESCE(MAX(position),-1) AS n FROM load_elements WHERE load_id=?").get(loadId) as {n:number}).n);
  const insLoadEl=db.prepare("INSERT INTO load_elements(load_id,element_id,position,orientation,intent,note,active_alloc) VALUES(?,?,?,?,?,?,1)");
  for(const item of added){pos++;insLoadEl.run(loadId,item.elementId,pos,defaultOrientation(getProjectElement(item.elementId)!.elementType),"Direct erection","Added at delivery");}
  // Release the reservation on every planned element that did NOT arrive.
  const release=db.prepare("UPDATE load_elements SET active_alloc=0 WHERE load_id=? AND element_id=?");
  for(const id of missing)release.run(loadId,id);
  // Received + added elements physically arrived → 'On site' (append element history).
  const toOnSite=db.prepare("UPDATE project_elements SET status='On site',actual_delivery_date=CASE WHEN actual_delivery_date='' THEN ? ELSE actual_delivery_date END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=? AND status IN ('Planned','Expected','Delivered') AND installed_report_id IS NULL");
  for(const id of [...received,...added.map((item)=>item.elementId)]){const element=getProjectElement(id);if(!element)continue;if(!["Planned","Expected","Delivered"].includes(element.status))continue;toOnSite.run(input.operationDate,id,projectId);recordElementHistory(id,element.status,"On site",input.operationDate,null,actor,`Received on load ${load.loadNumber}`);}
  db.prepare("UPDATE loads SET status='Accepted',acceptance_type=?,accepted_at=CURRENT_TIMESTAMP,accepted_by_id=?,accepted_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND project_id=?").run(input.acceptanceType,actor.id,actor.name,loadId,projectId);
  return receiptId;
}

export function runTransaction<T>(work: () => T): T {
  db.exec("BEGIN IMMEDIATE");
  try { const result=work(); db.exec("COMMIT"); return result; }
  catch (error) { db.exec("ROLLBACK"); throw error; }
}
