export const WEATHER_TIMEPOINTS=["07:00","10:00","14:00","17:00"] as const;
export type WeatherSnapshot={timepoint:string;temperature:number|null;conditionCode:number|null;condition:string;precipitation:number|null;windSpeed:number|null;windGust:number|null;provider:string;retrievedAt:string};
export interface WeatherProvider{load(input:{latitude:number;longitude:number;date:string;timezone:string}):Promise<WeatherSnapshot[]>}

export function weatherCondition(code:number|null){if(code===null)return"Unknown";if(code===0)return"Clear";if([1,2,3].includes(code))return"Cloudy";if([45,48].includes(code))return"Fog";if(code>=51&&code<=57)return"Drizzle";if(code>=61&&code<=67)return"Rain";if(code>=71&&code<=77)return"Snow";if(code>=80&&code<=82)return"Rain showers";if(code>=85&&code<=86)return"Snow showers";if(code>=95)return"Thunderstorm";return"Other";}
export function selectWeatherTimepoints(hourly:{time:string[];temperature_2m:Array<number|null>;weather_code:Array<number|null>;precipitation:Array<number|null>;wind_speed_10m:Array<number|null>;wind_gusts_10m:Array<number|null>},date:string,retrievedAt:string,provider="Open-Meteo"){return WEATHER_TIMEPOINTS.flatMap((timepoint)=>{const index=hourly.time.indexOf(`${date}T${timepoint}`);if(index<0)return[];const conditionCode=hourly.weather_code[index]??null;return[{timepoint,temperature:hourly.temperature_2m[index]??null,conditionCode,condition:weatherCondition(conditionCode),precipitation:hourly.precipitation[index]??null,windSpeed:hourly.wind_speed_10m[index]??null,windGust:hourly.wind_gusts_10m[index]??null,provider,retrievedAt}];});}

function numberOrNull(value:unknown){return typeof value==="number"&&Number.isFinite(value)?value:null;}
export function parseReportWeatherSnapshot(raw:string):WeatherSnapshot[]{if(!raw)return[];try{const parsed=JSON.parse(raw) as Array<Partial<WeatherSnapshot>>;if(!Array.isArray(parsed))return[];const seen=new Set<string>();return parsed.filter((row):row is Partial<WeatherSnapshot>&{timepoint:string;provider:string;retrievedAt:string}=>typeof row.timepoint==="string"&&WEATHER_TIMEPOINTS.includes(row.timepoint as typeof WEATHER_TIMEPOINTS[number])&&!seen.has(row.timepoint)&&typeof row.provider==="string"&&Boolean(row.provider.trim())&&typeof row.retrievedAt==="string"&&Boolean(row.retrievedAt.trim())&&(seen.add(row.timepoint),true)).sort((a,b)=>WEATHER_TIMEPOINTS.indexOf(a.timepoint as typeof WEATHER_TIMEPOINTS[number])-WEATHER_TIMEPOINTS.indexOf(b.timepoint as typeof WEATHER_TIMEPOINTS[number])).map((row)=>({timepoint:row.timepoint,temperature:numberOrNull(row.temperature),conditionCode:numberOrNull(row.conditionCode),condition:String(row.condition??"").slice(0,80),precipitation:numberOrNull(row.precipitation),windSpeed:numberOrNull(row.windSpeed),windGust:numberOrNull(row.windGust),provider:row.provider.slice(0,80),retrievedAt:row.retrievedAt.slice(0,40)}));}catch{return[];}}

export class OpenMeteoProvider implements WeatherProvider{
  async load(input:{latitude:number;longitude:number;date:string;timezone:string}){const url=openMeteoUrl(input),response=await fetch(url,{signal:AbortSignal.timeout(10000),cache:"no-store"});if(!response.ok)throw new Error("Weather provider request failed.");const data=await response.json() as {hourly?:Parameters<typeof selectWeatherTimepoints>[0]};if(!data.hourly)throw new Error("Weather provider returned no hourly data.");const rows=selectWeatherTimepoints(data.hourly,input.date,new Date().toISOString());if(!rows.length)throw new Error("Weather provider returned no requested timepoints.");return rows;}
}
export function openMeteoUrl(input:{latitude:number;longitude:number;date:string;timezone:string}){const today=new Intl.DateTimeFormat("en-CA",{timeZone:input.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),historical=input.date<today,base=historical?"https://archive-api.open-meteo.com/v1/archive":"https://api.open-meteo.com/v1/forecast",url=new URL(base);url.searchParams.set("latitude",String(input.latitude));url.searchParams.set("longitude",String(input.longitude));url.searchParams.set("start_date",input.date);url.searchParams.set("end_date",input.date);url.searchParams.set("timezone",input.timezone);url.searchParams.set("wind_speed_unit","ms");url.searchParams.set("hourly","temperature_2m,weather_code,precipitation,wind_speed_10m,wind_gusts_10m");return url;}
export function formatWeatherSummary(rows:WeatherSnapshot[]){return rows.map((row)=>`${row.timepoint} ${row.temperature===null?"—":`${row.temperature>0?"+":""}${row.temperature}°C`} ${row.condition} · ${row.windSpeed===null?"—":`${row.windSpeed} m/s`}`).join(" | ").slice(0,500);}
