import Link from "next/link";
import {MetricCard} from "../../components/portal/MetricCard";
import {ActivityFeed} from "../../components/portal/ActivityFeed";
import {PortalShell,PortalTopbar,StatusBadge} from "../../components/portal/PortalShell";
import {requireUser} from "../../lib/auth";
import {listDocuments,listEmployees,listProjectDocuments,listProjects,listReports} from "../../lib/repositories";
import {canManageProjectOperations} from "../../lib/permissions";
import {appToday} from "../../lib/datetime";
import {getPortalLanguage} from "../../lib/portal-locale";
import {portalText} from "../../data/portal-i18n";

export default async function PortalPage(){const user=await requireUser();const language=await getPortalLanguage();const t=(v:string)=>portalText(language,v);const canCreate=canManageProjectOperations(user);const projects=listProjects();const reports=listReports();const employees=listEmployees();const active=projects.filter(p=>p.status==="Active");const todayReports=reports.filter(r=>r.date===appToday());const important=[...listProjectDocuments(),...listDocuments()].filter(d=>!["Archived","Superseded"].includes(d.status)).length;return <PortalShell active="/portal">
  <PortalTopbar eyebrow={`PREFAB.LV · ${t("Operations")}`} title={`${t("Good morning")}, ${user.name}.`} action={canCreate?<Link className="os-primary-action" href="/portal/reports/new">+ {t("Create daily report")}</Link>:undefined}/>
  <section className="os-metrics-grid"><MetricCard value={active.length} label={t("Active projects")} note={t("Live database")}/><MetricCard value={employees.length} label={t("Employees / workers")} note={t("Across active projects")}/><MetricCard value={todayReports.length} label={t("Today's reports")} note={t("Submitted today")}/><MetricCard value={important} label={t("Important documents")} note={t("Current, review or draft")}/></section>
  <section className="os-dashboard-grid"><article className="os-panel os-panel-wide"><div className="os-panel-head"><div><p>{t("Operations").toUpperCase()}</p><h2>{t("Active projects")}</h2></div><Link href="/portal/projects">{t("View all")} →</Link></div><div className="os-project-list">{active.map(project=><Link className="os-project-row" href={`/portal/projects/${project.id}`} key={project.id}><div><strong>{project.name}</strong><span>{project.location} · {project.client}</span></div><div className="os-progress-wrap"><span>{project.progress}%</span><div className="os-progress"><i style={{width:`${project.progress}%`}}/></div></div><StatusBadge status={project.status} label={t(project.status)}/></Link>)}</div></article>
  <article className="os-panel"><div className="os-panel-head"><div><p>{t("Account").toUpperCase()}</p><h2>{user.role}</h2></div></div><div className="os-action-list"><div><span>01</span><div><strong>{user.email}</strong><small>{t("Authenticated session")}</small></div></div>{canCreate&&<Link href="/portal/reports/new"><span>02</span><div><strong>{t("Create daily report")}</strong><small>{t("Saves directly to database")}</small></div></Link>}</div></article>
  <article className="os-panel os-panel-wide"><div className="os-panel-head"><div><p>{t("Reporting").toUpperCase()}</p><h2>{t("Latest daily reports")}</h2></div><Link href="/portal/reports">{t("View all")} →</Link></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>{t("Project")}</th><th>{t("Date")}</th><th>{t("People")}</th><th>{t("Work completed")}</th><th>{t("Issues")}</th></tr></thead><tbody>{reports.slice(0,3).map(r=><tr key={r.id}><td><strong>{r.project}</strong></td><td>{r.date}</td><td>{r.people}</td><td>{r.work}</td><td>{r.issues}</td></tr>)}</tbody></table></div></article><article className="os-panel"><div className="os-panel-head"><div><p>{t("Audit").toUpperCase()}</p><h2>{t("Recent activity")}</h2></div></div><ActivityFeed limit={6}/></article></section>
</PortalShell>}
