import Link from "next/link";
import { MetricCard } from "../../components/portal/MetricCard";
import { ActivityFeed } from "../../components/portal/ActivityFeed";
import { PortalShell, PortalTopbar, StatusBadge } from "../../components/portal/PortalShell";
import { requireUser } from "../../lib/auth";
import { listProjects, listReports } from "../../lib/repositories";
import { canManageProjectOperations } from "../../lib/permissions";

export default async function PortalPage() {
  const user = await requireUser();
  const canCreateReports=canManageProjectOperations(user);
  const projects = listProjects(); const reports = listReports(); const active = projects.filter((p) => p.status === "Active");
  const people = active.reduce((sum,p) => sum + p.peopleToday, 0); const issues = reports.slice(0,2).reduce((sum,r) => sum + r.issues,0);
  return <PortalShell active="/portal"><PortalTopbar eyebrow="PREFAB.LV · Operations" title={`Good morning, ${user.name}.`} action={canCreateReports?<Link className="os-primary-action" href="/portal/reports/new">+ Daily report</Link>:undefined} /><section className="os-metrics-grid"><MetricCard value={active.length} label="Active projects" note="Live database" /><MetricCard value={people} label="People on site" note="Across active projects" /><MetricCard value="3" label="Deliveries today" note="Next at 10:30" /><MetricCard value={issues} label="Open issues" note={issues ? "Needs attention" : "No blockers"} /></section><section className="os-dashboard-grid"><article className="os-panel os-panel-wide"><div className="os-panel-head"><div><p>OPERATIONS</p><h2>Active projects</h2></div><Link href="/portal/projects">View all →</Link></div><div className="os-project-list">{active.map((project)=><Link className="os-project-row" href={`/portal/projects/${project.id}`} key={project.id}><div><strong>{project.name}</strong><span>{project.location} · {project.client}</span></div><div className="os-progress-wrap"><span>{project.progress}%</span><div className="os-progress"><i style={{width:`${project.progress}%`}} /></div></div><StatusBadge status={project.status} /></Link>)}</div></article><article className="os-panel"><div className="os-panel-head"><div><p>ACCOUNT</p><h2>{user.role}</h2></div></div><div className="os-action-list"><div><span>01</span><div><strong>{user.email}</strong><small>Authenticated session</small></div></div>{canCreateReports&&<Link href="/portal/reports/new"><span>02</span><div><strong>Create daily report</strong><small>Saves directly to database</small></div></Link>}</div></article><article className="os-panel os-panel-wide"><div className="os-panel-head"><div><p>REPORTING</p><h2>Latest daily reports</h2></div><Link href="/portal/reports">All reports →</Link></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Project</th><th>Date</th><th>People</th><th>Work completed</th><th>Issues</th></tr></thead><tbody>{reports.slice(0,3).map((r)=><tr key={r.id}><td><strong>{r.project}</strong></td><td>{r.date}</td><td>{r.people}</td><td>{r.work}</td><td>{r.issues}</td></tr>)}</tbody></table></div></article><article className="os-panel"><div className="os-panel-head"><div><p>AUDIT</p><h2>Recent activity</h2></div></div><ActivityFeed limit={6}/></article></section></PortalShell>;
}
